### PR TITLE
Remove warnings on CLI start

### PR DESCRIPTION
**Pull request by CTY-git**

### CODE REVIEW

**Comment by patched-admin** [comment]
The reviewer highlights concerns about the addition of 'import warnings' and 'warnings.simplefilter("ignore")' in the code, as it could suppress important warning messages that may aid in debugging and issue identification. They advise reconsidering the use of 'warnings.simplefilter("ignore")' to ensure critical information is not accidentally ignored. Additionally, the removal of the `register_callbacks` method without updating the `__do_callbacks` method to account for the change may result in a runtime error when `__do_callbacks` is invoked without any callbacks in the list.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  The addition of 'import warnings' and 'warnings.simplefilter("ignore")' in the code could potentially hide important warning messages that could help in debugging or identifying issues. It's important to carefully consider the implications of suppressing warnings and ensure that it is done intentionally with a valid reason. Please reconsider the usage of 'warnings.simplefilter("ignore")' and evaluate if any critical information is being unintentionally ignored.

</div>

<div markdown="1">

* File changed: [patchwork/common/utils/progress_bar.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-f9e2e363989f71f4f2e632202cd7f12ac99708683bbb794a14f010c06cdc7841)
  The `register_callbacks` method has been removed, which was used to extend the callbacks list. However, the method `__do_callbacks` still exists and is trying to iterate over the now non-existent callbacks list. This could potentially cause a runtime error when `__do_callbacks` is called without any callbacks present in the list.

</div>

**Comment by patched-admin** [comment]
In the pull request review, it was noted that adding 'import warnings' and 'warnings.simplefilter('ignore')' in the app.py file could suppress important warnings that could indicate errors in the code, and it was recommended to handle warnings appropriately rather than ignore them. However, the code modifications in progress_bar.py were deemed fine, with no potential bugs or new security vulnerabilities introduced, and the code was found to adhere to the original coding standards in the pull request.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  The addition of 'import warnings' and 'warnings.simplefilter('ignore')' in app.py file can potentially suppress important warnings that could indicate errors in the code. It's important to handle warnings appropriately, rather than ignoring them. Please consider revising this part of the code to ensure that important warnings are not being overlooked.

</div>

<div markdown="1">

* File changed: [patchwork/common/utils/progress_bar.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-f9e2e363989f71f4f2e632202cd7f12ac99708683bbb794a14f010c06cdc7841)
  The code modifications in progress_bar.py seem fine. There are no potential bugs or new security vulnerabilities introduced in the changes. The code adheres to the original coding standards in the pull request.

</div>

**Comment by patched-admin** [comment]
The pull request review highlights the removal of the register_callbacks and suppress_warnings methods and their calls, cautioning that this could introduce bugs if these functionalities were necessary for the progress bar's functioning. The code modifications are deemed to adhere to coding standards, with no new bugs or security vulnerabilities introduced. However, a potential bug is noted with a specific condition, suggesting a clearer check. Additionally, it is recommended to address the commented out code on line 52 to prevent confusion for future developers. It is crucial to ensure that the removal of these methods and calls does not impact the expected behavior of the progress bar.

------

<div markdown="1">

* File changed: [patchwork/common/utils/progress_bar.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-f9e2e363989f71f4f2e632202cd7f12ac99708683bbb794a14f010c06cdc7841)
  The code modifications in this pull request have removed the register_callbacks method and the suppress_warnings method along with their respective calls. If these functionalities were in use before and needed for the functioning of the progress bar, their removal could potentially introduce bugs. It's important to ensure that removing these methods and calls will not impact the expected behavior of the progress bar.

</div>

<div markdown="1">

* File changed: [patchwork/logger.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-20f986b5bd504db976ce63bea58d28a56004397cc82fddf3e2230f3a7c53b8c6)
  The code modifications in the pull request look good. There are no potential bugs or security vulnerabilities introduced. The new code adheres to the original coding standards in the pull request.

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/CallLLM.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-06684f9c0b7bb0e746ea0a10fd6f7cbe2e671ff44a4069e16cdf4faae231c409)
  Potential bug: The condition 'if -1 < self.call_limit < prompt_length' can lead to unexpected behaviour. It would be cleaner to explicitly check 'if prompt_length > self.call_limit' instead. The removal of 'self.call_limit > 0' condition seems reasonable as it is redundant with the previous check.

</div>

<div markdown="1">

* File changed: [patchwork/steps/PreparePR/PreparePR.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-9d9d7377695552b3c8a8eb4f35311a23d718365621376813df7720d381c7827c)
  The commented out code (line 52) should be removed or updated to reflect the actual logic required for the line numbers when exceeding diff chunk. This could potentially cause confusion for other developers in the future.

</div>

**Comment by patched-admin** [comment]
The pull request review highlights potential issues with the code modifications, such as the removal of the `register_callbacks` and `__suppress_warnings` methods and potential impact on functionality and error handling. Additionally, concerns are raised about a possible bug introduced in the `__get_filter` function due to assigning the log level name directly, rather than evaluating it first. The handling of negative values for `self.call_limit` and adherence to original coding standards are also pointed out as areas for improvement before merging the changes. Furthermore, the commented out code for updating `placeholder_inner_text` is flagged for incorrect syntax and confusion in indentation, requiring verification and correction before merging.

------

<div markdown="1">

* File changed: [patchwork/common/utils/progress_bar.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-f9e2e363989f71f4f2e632202cd7f12ac99708683bbb794a14f010c06cdc7841)
  The code modifications have removed the `register_callbacks` method along with its usage, as well as the `__suppress_warnings` method which suppressed warnings. This removal could lead to potential issues in terms of maintaining callback functionality and dealing with warnings. It's important to ensure that these changes do not affect the intended behavior or the error handling mechanisms in the program.

</div>

<div markdown="1">

* File changed: [patchwork/logger.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-20f986b5bd504db976ce63bea58d28a56004397cc82fddf3e2230f3a7c53b8c6)
  The change made to the __get_filter function in logger.py could potentially introduce a bug. The code snippet 'log_level = logging.getLevelName(log_level)' may cause an issue as it assigns the log level name instead of evaluating it first. This could result in unexpected behavior. It would be better if the original condition 'log_level = logging.TRACE if log_level == 'TRACE' else logging.getLevelName(log_level)' is retained for correctness. Also, the addition of 'warnings.simplefilter('ignore')' does not adhere to the original coding standards in the pull request. Please consider these points before merging.

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/CallLLM.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-06684f9c0b7bb0e746ea0a10fd6f7cbe2e671ff44a4069e16cdf4faae231c409)
  The code modification in this pull request does not properly handle the case when self.call_limit is set to a negative value, which might result in unexpected behavior. It is recommended to check and handle the case when self.call_limit is less than 0. Additionally, the removal of the check 'if self.call_limit > 0' might impact the behavior, and it would be beneficial to revisit the logic and ensure that it still functions correctly as per the original coding standards.

</div>

<div markdown="1">

* File changed: [patchwork/steps/PreparePR/PreparePR.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-9d9d7377695552b3c8a8eb4f35311a23d718365621376813df7720d381c7827c)
  The commented out code for updating the placeholder_inner_text variable seems to be incorrect syntax. It seems like there might be confusion in the indentation and commented lines within this block. Please verify and correct the syntax before merging.

</div>

**Comment by patched-admin** [comment]
The removal of the __suppress_warnings method in the pull request could potentially lead to bugs as warnings that were previously suppressed will now be visible, impacting application stability. The addition of 'warnings.simplefilter("ignore")' in the 'init_cli_logger' function may suppress important warnings that could aid in debugging. Additionally, there is a potential bug in the code with the condition 'if -1 < self.call_limit < prompt_length' which could lead to unexpected behavior. Correcting the indentation of the commented out code in the `run` function of PreparePR.py is also necessary to ensure proper execution. It is crucial to review the necessity of changes related to suppressing warnings and verify the logic of conditions to prevent issues in processing prompts.

------

<div markdown="1">

* File changed: [patchwork/common/utils/progress_bar.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-f9e2e363989f71f4f2e632202cd7f12ac99708683bbb794a14f010c06cdc7841)
  The removal of the __suppress_warnings method may cause potential bugs as it was suppressing warnings using warnings.simplefilter('ignore'). Without this, any warnings that were being suppressed before will now be visible. It's important to consider if there were specific reasons for suppressing warnings and if they should be handled differently now. Additionally, the code modifications do not adhere to the original standards where warnings were being managed. It's recommended to revisit the necessity of suppressing warnings and handle them appropriately to ensure application stability.

</div>

<div markdown="1">

* File changed: [patchwork/logger.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-20f986b5bd504db976ce63bea58d28a56004397cc82fddf3e2230f3a7c53b8c6)
  The modification to add 'warnings.simplefilter("ignore")' in the 'init_cli_logger' function could potentially suppress important warnings that could help in debugging or identifying issues in the future. It is important to be cautious when silencing warnings as it might hide potential bugs or unexpected behavior in the code. It's recommended to review the necessity of this change and ensure that critical warnings are not being hidden.

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/CallLLM.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-06684f9c0b7bb0e746ea0a10fd6f7cbe2e671ff44a4069e16cdf4faae231c409)
  The code modifications in the pull request seem to contain a potential bug. The condition 'if -1 < self.call_limit < prompt_length' might not work as intended, as it could lead to unexpected behavior when trying to filter prompts based on the call limit. It would be better to ensure the logic of this check is correct to avoid any issues in processing the prompts.

</div>

<div markdown="1">

* File changed: [patchwork/steps/PreparePR/PreparePR.py](https://github.com/patched-codes/patchwork/pull/502/files#diff-9d9d7377695552b3c8a8eb4f35311a23d718365621376813df7720d381c7827c)
  The commented out code within the `run` function of PreparePR.py seems to have caused an indentation issue as it is not aligned properly. This may imply that the code logic inside the if block is not executed as intended. It would be advisable to correct the indentation to ensure the code functions correctly when necessary.

</div>

**Review by codelion — APPROVED** [review]

**Pull request merged**
