### PR TITLE
Add Tracing

### PR DESCRIPTION
**Pull request by CTY-git**

### CODE REVIEW

**Comment by patched-admin** [comment]
This code change introduces a new command-line option `disable_telemetry` in the CLI, which is a boolean flag to turn off telemetry. It also adds a conditional check in the code to send public telemetry based on this flag before running the patchflow instance. In patched.py, the patchwork client has been updated to include several imports and a new method for handling telemetry inputs and sending public telemetry data. In utils.py, a new function `is_container()` has been added to check for specific files and system paths to determine if the script is running in a container environment, returning `True` if detected, with a comment for possible future development related to cgroup v2 detection.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [This diff adds a new CLI option called `disable_telemetry` which is a boolean flag to disable telemetry. An additional check is added to conditionally send public telemetry based on the `disable_telemetry` flag before running the patchflow instance.](https://github.com/patched-codes/patchwork/pull/203/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/common/client/patched.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)
  [The patchwork client in patched.py has been updated to include imports for asyncio, hashlib, http.client, json, platform, and uuid. Additionally, a method for handling telemetry inputs and sending public telemetry data has been implemented.](https://github.com/patched-codes/patchwork/pull/203/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)

</div>

<div markdown="1">

* File changed: [patchwork/common/utils.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-64d094a0b6e480bc072eadafd1516f4c70f777242a3b68df96ec8e263174e35d)
  [This diff in the `utils.py` file adds a new function `is_container()` that checks for the presence of certain files and system paths to determine if the script is running within a container environment, returning `True` if it is detected, and includes a comment for future development regarding cgroup v2 detection.](https://github.com/patched-codes/patchwork/pull/203/files#diff-64d094a0b6e480bc072eadafd1516f4c70f777242a3b68df96ec8e263174e35d)

</div>

**Comment by patched-admin** [comment]
The first code change introduces a new command line option to disable telemetry in the app.py file's CLI function, ensuring telemetry is not sent when interacting with the PatchedClient class. The second change in patched.py involves importing various modules and adding a new allowed telemetry key "model," as well as functions for handling and sending telemetry data asynchronously. Lastly, the update in utils.py adds a new function `is_container` to detect container-related files or cgroups, currently supporting cgroup v1 detection and indicating the potential need for cgroup v2 support in the future.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The diff adds a new command line option for disabling telemetry in the CLI function of the app.py file. If the disable_telemetry flag is enabled, telemetry will not be sent when interacting with the PatchedClient class.](https://github.com/patched-codes/patchwork/pull/203/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/common/client/patched.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)
  [The diff in the patched.py file includes additions of imports such as asyncio, hashlib, http.client, json, platform, and uuid, as well as the typing module. It also adds a new allowed telemetry key "model" and functions related to handling and sending telemetry data to a specified URL using threading and asyncio.](https://github.com/patched-codes/patchwork/pull/203/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)

</div>

<div markdown="1">

* File changed: [patchwork/common/utils.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-64d094a0b6e480bc072eadafd1516f4c70f777242a3b68df96ec8e263174e35d)
  [The diff in the `utils.py` file adds a new function `is_container` to check for the presence of container-related files or cgroups, returning `True` if detected. The function currently only handles cgroup v1 detection and hints at the need for support for cgroup v2 in the future.](https://github.com/patched-codes/patchwork/pull/203/files#diff-64d094a0b6e480bc072eadafd1516f4c70f777242a3b68df96ec8e263174e35d)

</div>

**Review by codelion — APPROVED** [review]

**Comment by patched-admin** [comment]
The code changes include adding a new option in the CLI to enable or disable telemetry, sending telemetry data using the PatchedClient class, updating the patched.py file to include imports for new modules and adding a method to send telemetry data to a specified URL, adding a new function to check if code is running in a container, and updating the version of the tool "patchwork-cli" in the pyproject.toml file from 0.0.16 to 0.0.17.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [This diff adds a new option in the CLI called "disable_telemetry" which is a flag to enable or disable telemetry. If telemetry is not disabled, it will send public telemetry using the PatchedClient class before running the patchflow_instance.](https://github.com/patched-codes/patchwork/pull/203/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/common/client/patched.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)
  [The code in `patchwork/common/client/patched.py` was updated to include imports for new modules like `asyncio`, `hashlib`, `http.client`, `json`, `platform`, `uuid`, and functions related to handling telemetry data. Additionally, a new method `send_public_telemetry` was added to send telemetry data to a specified URL with authorization.](https://github.com/patched-codes/patchwork/pull/203/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)

</div>

<div markdown="1">

* File changed: [patchwork/common/utils.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-64d094a0b6e480bc072eadafd1516f4c70f777242a3b68df96ec8e263174e35d)
  [This diff adds a new function `is_container` to the `utils.py` file in the `patchwork/common` directory. The function checks for specific files and paths to determine if the code is running inside a container, returning True if it is detected.](https://github.com/patched-codes/patchwork/pull/203/files#diff-64d094a0b6e480bc072eadafd1516f4c70f777242a3b68df96ec8e263174e35d)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/203/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version of the tool "patchwork-cli" in the `pyproject.toml` file has been updated from 0.0.16 to 0.0.17.](https://github.com/patched-codes/patchwork/pull/203/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

**Comment by patched-admin** [comment]
The code changes include adding a new CLI option "--disable-telemetry" with a default value of False, allowing users to control telemetry data collection. Additional modules like asyncio, hashlib, http.client, json, platform, uuid were imported and new methods for handling telemetry data were added, along with a constant for allowed telemetry keys. A new function `is_container()` was introduced to check for container environment conditions, returning `True` if conditions are met. The code also now uses `Path(self.folder_path)` from the `pathlib` module to set `code_file_path`, improving readability. Lastly, the project version in pyproject.toml has been updated to 0.0.17 while other fields remain unchanged.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [A new CLI option "--disable-telemetry" has been added to the command line interface with a default value of False, allowing users to disable telemetry. This option is used to conditionally send public telemetry data based on the value of "disable_telemetry" within the cli function.](https://github.com/patched-codes/patchwork/pull/203/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/common/client/patched.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)
  [The code changes include importing additional modules like asyncio, hashlib, http.client, json, platform, uuid, and adding new methods for handling and sending telemetry data, as well as a new constant for allowed telemetry keys.](https://github.com/patched-codes/patchwork/pull/203/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)

</div>

<div markdown="1">

* File changed: [patchwork/common/utils.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-64d094a0b6e480bc072eadafd1516f4c70f777242a3b68df96ec8e263174e35d)
  [Added a new function `is_container()` that checks for the presence of specific files and conditions in the filesystem to determine if the code is running inside a container environment. The function returns `True` if the conditions are met and `False` otherwise, with a placeholder for detecting cgroup v2 in the future.](https://github.com/patched-codes/patchwork/pull/203/files#diff-64d094a0b6e480bc072eadafd1516f4c70f777242a3b68df96ec8e263174e35d)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallCode2Prompt/CallCode2Prompt.py](https://github.com/patched-codes/patchwork/pull/203/files#diff-e3e053c380057dbcade07db27ed6d45e7722d7d58f51850e196dc6b62cc2fbb4)
  [The code in the file is importing the `Path` class from the `pathlib` module. Instead of directly performing operations on `folder_path`, it now uses `Path(self.folder_path)` to set the `code_file_path`, enhancing readability and maintainability.](https://github.com/patched-codes/patchwork/pull/203/files#diff-e3e053c380057dbcade07db27ed6d45e7722d7d58f51850e196dc6b62cc2fbb4)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/203/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version of the project "patchwork-cli" in the pyproject.toml file has been updated from 0.0.16 to 0.0.17, while the other fields remain unchanged.](https://github.com/patched-codes/patchwork/pull/203/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

**Pull request merged**
