### PR TITLE
Added patchflow to generate usage example

### PR DESCRIPTION
**Pull request by plon-Susk7**
## PR Checklist

- [x] The commit message follows our guidelines: [Code of conduct](https://github.com/patched-codes/patchwork/blob/main/CODE_OF_CONDUCT.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] Does this PR introduce a breaking change?
- [ ] Include PR in release notes?

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Build /CI
- [ ] Documentation
- [ ] Others

## What is the current behavior?

No patchflow to generate usage example.

Issue Number: #878 

## What is the new behavior?

This PR introduces a new patchflow that generates usage example when provided with folder_path as argument. 

## Other information

### CODE REVIEW

**Review by CTY-git — COMMENTED** [review]
Hi can you generate a usage example with the patchflow? Thanks.

**Comment by plon-Susk7** [comment]
> Hi can you generate a usage example with the patchflow? Thanks.

https://github.com/plon-Susk7/patchwork/pull/5
This was usage example for GenerateUnitTests patch

**Comment by CTY-git** [comment]
> > Hi can you generate a usage example with the patchflow? Thanks.
> 
> [plon-Susk7#5](https://github.com/plon-Susk7/patchwork/pull/5) This was usage example for GenerateUnitTests patch

patchflows are meant to be run from the CLI, so this new `GenerateUnitTests` patchflow only generates example code usage?

**Comment by plon-Susk7** [comment]
> > > Hi can you generate a usage example with the patchflow? Thanks.
> > 
> > 
> > [plon-Susk7#5](https://github.com/plon-Susk7/patchwork/pull/5) This was usage example for GenerateUnitTests patch
> 
> patchflows are meant to be run from the CLI, so this new `GenerateUnitTests` patchflow only generates example code usage?

yes

**Comment by CTY-git** [comment]
@plon-Susk7 can you try generating a example for a js file as well?

**Comment by plon-Susk7** [comment]
Here's example for js file
https://github.com/plon-Susk7/patchwork/pull/5/files
```js
class VersionBumper {
    constructor(initialVersion = "0.1.0") {
      if (!this.isValidVersion(initialVersion)) {
        throw new Error("Invalid version format. Use Semantic Versioning (MAJOR.MINOR.PATCH).");
      }
      this.version = initialVersion;
    }
  
    /**
     * Validate the version string
     * @param {string} version
     * @returns {boolean}
     */
    isValidVersion(version) {
      return /^\d+\.\d+\.\d+$/.test(version);
    }
  
    /**
     * Get the current version
     * @returns {string}
     */
    getVersion() {
      return this.version;
    }
  
    /**
     * Bump the version based on the type
     * @param {string} type - "major", "minor", or "patch"
     * @returns {string} - New version
     */
    bump(type) {
      const [major, minor, patch] = this.version.split(".").map(Number);
  
      let newVersion;
      switch (type) {
        case "major":
          newVersion = `${major + 1}.0.0`;
          break;
        case "minor":
          newVersion = `${major}.${minor + 1}.0`;
          break;
        case "patch":
          newVersion = `${major}.${minor}.${patch + 1}`;
          break;
        default:
          throw new Error('Invalid bump type. Use "major", "minor", or "patch".');
      }
  
      this.version = newVersion;
      return this.version;
    }
  
    /**
     * Set the version explicitly
     * @param {string} version
     */
    setVersion(version) {
      if (!this.isValidVersion(version)) {
        throw new Error("Invalid version format. Use Semantic Versioning (MAJOR.MINOR.PATCH).");
      }
      this.version = version;
    }
  
    /**
     * Generate a tag for the version
     * @returns {string}
     */
    generateTag(prefix = "v") {
      return `${prefix}${this.version}`;
    }
  }
  
  export default VersionBumper;
  
```

**Comment by plon-Susk7** [comment]
> @plon-Susk7 can you try generating a example for a js file as well?
> 
> Also please change the patchflow name to GenerateCodeUsageExample instead. In addition please fix the merge conflicts. Thank you.

Done :+1:

**Review by CTY-git — APPROVED** [review]
LGTM

**Pull request merged**
