### PR TITLE
update configs default to force push commits

### PR DESCRIPTION
**Pull request by codelion**

### CODE REVIEW

**Comment by patched-admin** [comment]
The default setting for forcing PR creation in the file `defaults.yml` was updated in this patch to change the value from `false` to `true`, indicating that PR creation can now be forced automatically.

------

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)
  [The default setting for forcing PR creation in the file `defaults.yml` was changed from `false` to `true` in this patch.](https://github.com/patched-codes/patchwork/pull/80/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)
  [The change in the defaults.yml file sets "force_pr_creation" to true instead of false, indicating that PR creation can be forced.](https://github.com/patched-codes/patchwork/pull/80/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)
  [The default value for the 'force_pr_creation' setting in the defaults.yml file has been changed from false to true, potentially allowing for the automatic creation of pull requests.](https://github.com/patched-codes/patchwork/pull/80/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)

</div>

**Review by CTY-git — APPROVED** [review]

**Comment by patched-admin** [comment]
The code changes in the defaults.yml file now ensure that the 'force_pr_creation' option is set to 'true' instead of 'false, allowing for automatic pull requests to be forced when this feature is enabled in the DependencyUpgrade module of the patchflows directory. Additionally, the code now requires the 'libraries_api_key' to always be explicitly provided in the inputs dictionary.

------

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)
  [The changes in the defaults.yml file now set the 'force_pr_creation' option to 'true' instead of 'false'. This means that automatic pull requests will now be forced to be created when this feature is enabled.](https://github.com/patched-codes/patchwork/pull/80/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)
  [The diff in the defaults.yml file in the DependencyUpgrade module of the patchflows directory changes the value of `force_pr_creation` from false to true, allowing for forced PR creation.](https://github.com/patched-codes/patchwork/pull/80/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)
  [In the defaults.yml file, the "force_pr_creation" variable was changed from false to true, allowing for the generation of pull requests.](https://github.com/patched-codes/patchwork/pull/80/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)

</div>

<div markdown="1">

* File changed: [patchwork/steps/ExtractDiff/ExtractDiff.py](https://github.com/patched-codes/patchwork/pull/80/files#diff-9fdaa922ef15dd0700720e73e58c6bd18c8ab40586f9f35e10ea1046ce5f6d32)
  [The diff removes the code that sets the 'libraries_api_key' from either the inputs or the environment if not already set, indicating that the 'libraries_api_key' should now always be provided explicitly in the inputs dictionary.](https://github.com/patched-codes/patchwork/pull/80/files#diff-9fdaa922ef15dd0700720e73e58c6bd18c8ab40586f9f35e10ea1046ce5f6d32)

</div>

**Comment by patched-admin** [comment]
In this code change, the default value for the `force_pr_creation` option in the `defaults.yml` file has been modified from `false` to `true`, indicating that Pull Requests will be automatically generated for dependency upgrades without user confirmation. Additionally, the ResolveIssue.py file has been updated to include a new function called PreparePR and to set a pull request header with fixed issue information before creating the pull request. Finally, the code snippet removes the setting of 'libraries_api_key' from inputs or environment if not already set, assuming it must be explicitly provided in the 'inputs' dictionary for initializing the 'ExtractDiff' class.

------

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)
  [The default value for the `force_pr_creation` option in the `defaults.yml` file has been changed from `false` to `true` in this patch.](https://github.com/patched-codes/patchwork/pull/80/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)
  [The default value for `force_pr_creation` in the `defaults.yml` file has been changed from `false` to `true`, indicating that Pull Requests will be created for dependency upgrades without user confirmation.](https://github.com/patched-codes/patchwork/pull/80/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)
  [The default value for the `force_pr_creation` option in the `defaults.yml` file was changed from `false` to `true`, enabling the generation of pull requests to be forced when running the script.](https://github.com/patched-codes/patchwork/pull/80/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/ResolveIssue/ResolveIssue.py](https://github.com/patched-codes/patchwork/pull/80/files#diff-cb242c756a19ba4340510df69970f62fea6ab132b61e527fb35d3d92377454c7)
  [In the ResolveIssue.py file, a new function called PreparePR was added to prepare a pull request header in line 14. Additionally, in line 106, the script now sets a pull request header with information about the fixed issue before creating the pull request.](https://github.com/patched-codes/patchwork/pull/80/files#diff-cb242c756a19ba4340510df69970f62fea6ab132b61e527fb35d3d92377454c7)

</div>

<div markdown="1">

* File changed: [patchwork/steps/ExtractDiff/ExtractDiff.py](https://github.com/patched-codes/patchwork/pull/80/files#diff-9fdaa922ef15dd0700720e73e58c6bd18c8ab40586f9f35e10ea1046ce5f6d32)
  [The code snippet removes setting the 'libraries_api_key' from inputs or environment if not already set before initializing the 'ExtractDiff' class, as it is now assumed to be a required key that needs to be explicitly provided in the 'inputs' dictionary.](https://github.com/patched-codes/patchwork/pull/80/files#diff-9fdaa922ef15dd0700720e73e58c6bd18c8ab40586f9f35e10ea1046ce5f6d32)

</div>

**Comment by patched-admin** [comment]
In the recent code changes, the 'contextlib' module import was removed from the utils.py file in the patchwork/common directory. Additionally, in the defaults.yml file, the force_pr_creation setting was modified from false to true, indicating that pull requests will now be forced when this configuration option is enabled. Another change in the defaults.yml file switched the force_pr_creation option from false to true, potentially affecting pull request creation behavior. Furthermore, the default value for force_pr_creation was updated from false to true in the defaults.yml file under the patchflows/GenerateREADME directory. A new module named PreparePR was added to prepare pull requests with specific headers mentioning the fixed issue before creating them. Moreover, the 'os' module import was removed from ExtractDiff.py, and the section setting 'libraries_api_key' was deleted. Lastly, the version number for the "patchwork-cli" project in the pyproject.toml file has been increased from 0.0.7 to 0.0.87.

------

<div markdown="1">

* File changed: [patchwork/common/utils.py](https://github.com/patched-codes/patchwork/pull/80/files#diff-64d094a0b6e480bc072eadafd1516f4c70f777242a3b68df96ec8e263174e35d)
  [In the utils.py file in the patchwork/common directory, the 'contextlib' module import has been removed.](https://github.com/patched-codes/patchwork/pull/80/files#diff-64d094a0b6e480bc072eadafd1516f4c70f777242a3b68df96ec8e263174e35d)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)
  [In the defaults.yml file, the force_pr_creation setting has been changed from false to true, indicating that the creation of pull requests will be forced when this configuration option is enabled.](https://github.com/patched-codes/patchwork/pull/80/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)
  [In the `defaults.yml` file, the `force_pr_creation` option has been changed from `false` to `true`, potentially indicating a change in behavior related to creating pull requests when running this script.](https://github.com/patched-codes/patchwork/pull/80/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/defaults.yml](https://github.com/patched-codes/patchwork/pull/80/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)
  [The default value for `force_pr_creation` has been changed from false to true in the `defaults.yml` file under the `patchflows/GenerateREADME` directory.](https://github.com/patched-codes/patchwork/pull/80/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/ResolveIssue/ResolveIssue.py](https://github.com/patched-codes/patchwork/pull/80/files#diff-cb242c756a19ba4340510df69970f62fea6ab132b61e527fb35d3d92377454c7)
  [The code has been updated to include a new module called PreparePR. This module is used to prepare a pull request with a specific header that mentions the issue being fixed before creating the actual pull request.](https://github.com/patched-codes/patchwork/pull/80/files#diff-cb242c756a19ba4340510df69970f62fea6ab132b61e527fb35d3d92377454c7)

</div>

<div markdown="1">

* File changed: [patchwork/steps/ExtractDiff/ExtractDiff.py](https://github.com/patched-codes/patchwork/pull/80/files#diff-9fdaa922ef15dd0700720e73e58c6bd18c8ab40586f9f35e10ea1046ce5f6d32)
  [The import statement for the 'os' module has been removed from the code in ExtractDiff.py, and the section that sets 'libraries_api_key' from the environment or inputs has been deleted.](https://github.com/patched-codes/patchwork/pull/80/files#diff-9fdaa922ef15dd0700720e73e58c6bd18c8ab40586f9f35e10ea1046ce5f6d32)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/80/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version number in the pyproject.toml file for the "patchwork-cli" project has been updated from 0.0.7 to 0.0.87.](https://github.com/patched-codes/patchwork/pull/80/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

**Pull request merged**
