### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by codelion**

### CODE REVIEW

**Comment by patched-admin** [comment]
The README.md file was updated to change the prompt for users to summarize code change descriptions in 1 paragraph instead of crafting a well-structured message based on a code diff review. The "id" field was also updated to "diffreview_summary" and the prompt content for the user role was adjusted to reflect this modification. This change aims to streamline the process of summarizing code changes for users by providing a clear and concise prompt in the template.

------

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/36/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  [Updated a sample prompt template in the README.md file to prompt users to summarize code change descriptions in 1 paragraph instead of creating a well-structured message based on a code diff review. The "id" field was changed to "diffreview_summary" and the prompt content for the user role was modified accordingly.](https://github.com/patched-codes/patchwork/pull/36/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

</div>

**Comment by patched-admin** [comment]
The README.md file diff modifies the JSON template for a prompt with the ID "ReviewPR" to "diffreview_summary" and updates the user prompt content to instruct summarizing code change descriptions in one paragraph using the https://github.com/patched-codes/patchwork/pull/36/files#diff-fb040b34d4fe77c6ecab639930a2f2310d1bd88ca4f8a76eead37f83a921f3d4 variable. Additionally, the diff changes the model parameter to 'deepseek-coder-6.7b-instruct.Q4_K_M.gguf' and adds the chat format option 'chatml' to the command for running llama.cpp server locally. Another change includes adding the argument `--chat_format chatml` to the `python3 -m llama_cpp.server` command for running inference on CPU using llama-cpp.

------

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/36/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  [The diff in the README.md file changes the JSON template for a prompt with the ID "ReviewPR" to "diffreview_summary" and modifies the user prompt content to instruct the user to summarize code change descriptions in one paragraph, using the variable https://github.com/patched-codes/patchwork/pull/36/files#diff-fb040b34d4fe77c6ecab639930a2f2310d1bd88ca4f8a76eead37f83a921f3d4.](https://github.com/patched-codes/patchwork/pull/36/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/README.md](https://github.com/patched-codes/patchwork/pull/36/files#diff-f0443aa41f76d4c2dbc8d732153c131c65ebb2fa56018367926f271da2ca6c0f)
  [The diff in the README.md file updates the command for running llama.cpp server to include the chat format parameter "--chat_format chatml" and change the model parameter from "deepseek-coder-6.7b-instruct.Q4_0.gguf" to "deepseek-coder-6.7b-instruct.Q4_K_M.gguf".](https://github.com/patched-codes/patchwork/pull/36/files#diff-f0443aa41f76d4c2dbc8d732153c131c65ebb2fa56018367926f271da2ca6c0f)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/README.md](https://github.com/patched-codes/patchwork/pull/36/files#diff-631fe6035df65d9352bb9ceeb4254e991a0eb35cbda7aa71780a10cec67cc7b8)
  [Changed the model version in the python command to 'deepseek-coder-6.7b-instruct.Q4_K_M.gguf' and added the chat format option 'chatml' to the command in the README file for running inference using llama.cpp locally.](https://github.com/patched-codes/patchwork/pull/36/files#diff-631fe6035df65d9352bb9ceeb4254e991a0eb35cbda7aa71780a10cec67cc7b8)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/README.md](https://github.com/patched-codes/patchwork/pull/36/files#diff-32d4d49395e98f9a8958fefd0510777e2f157f0c0cbd752fb98ccb485303cbd3)
  [The diff in the README.md file updates a command in the instructions for running inference on CPU locally using the llama-cpp package. The update adds the argument `--chat_format chatml` to the `python3 -m llama_cpp.server` command.](https://github.com/patched-codes/patchwork/pull/36/files#diff-32d4d49395e98f9a8958fefd0510777e2f157f0c0cbd752fb98ccb485303cbd3)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/PRReview/README.md](https://github.com/patched-codes/patchwork/pull/36/files#diff-0f006562635180059ae21ff8c7a78e33b05ea0532109250429e04f437893a92c)
  [The diff shows a change in the command for running the llama.cpp server locally, including adding the `--chat_format chatml` parameter to the command. This parameter seems to modify how the server handles chat format during the inference process.](https://github.com/patched-codes/patchwork/pull/36/files#diff-0f006562635180059ae21ff8c7a78e33b05ea0532109250429e04f437893a92c)

</div>

**Comment by codelion** [comment]
@CTY-git I tried to update the docs to make them in line with the recent changes. Can you take a quick look at the repo readme and the patchflow readmes to see if there is something missing?

**Comment by patched-admin** [comment]
The changes in the README.md file involve updating the ID in a JSON prompt template to "diffreview_summary" to summarize code change descriptions in one paragraph. Additionally, the llama-CPP server command is modified to include the model 'deepseek-coder-6.7b-instruct.Q4_K_M.gguf' and '--chat_format chatml' option. Instructions for setting severity and compatibility thresholds for fixing vulnerabilities in the code are also included in the patch.

------

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/36/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  [The diff in the README.md file changed the ID in a JSON prompt template from "ReviewPR" to "diffreview_summary" and updated the user prompt content to summarize code change descriptions in one paragraph.](https://github.com/patched-codes/patchwork/pull/36/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/README.md](https://github.com/patched-codes/patchwork/pull/36/files#diff-f0443aa41f76d4c2dbc8d732153c131c65ebb2fa56018367926f271da2ca6c0f)
  [The patch in the README file updates the llama-CPP server command by changing the model from 'deepseek-coder-6.7b-instruct.Q4_0.gguf' to 'deepseek-coder-6.7b-instruct.Q4_K_M.gguf' and adds the '--chat_format chatml' option. Additionally, it includes instructions on how to set severity and compatibility thresholds for fixing vulnerabilities in the code.](https://github.com/patched-codes/patchwork/pull/36/files#diff-f0443aa41f76d4c2dbc8d732153c131c65ebb2fa56018367926f271da2ca6c0f)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/README.md](https://github.com/patched-codes/patchwork/pull/36/files#diff-631fe6035df65d9352bb9ceeb4254e991a0eb35cbda7aa71780a10cec67cc7b8)
  [The diff in the README.md file shows a change in the command to run the OpenAI compatible web server using llama.cpp locally. The modification includes adding the `--chat_format chatml` option to the existing command.](https://github.com/patched-codes/patchwork/pull/36/files#diff-631fe6035df65d9352bb9ceeb4254e991a0eb35cbda7aa71780a10cec67cc7b8)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/README.md](https://github.com/patched-codes/patchwork/pull/36/files#diff-32d4d49395e98f9a8958fefd0510777e2f157f0c0cbd752fb98ccb485303cbd3)
  [The diff in the README file updates the command for running llama.cpp server to include the `--chat_format chatml` option along with specifying a different model.](https://github.com/patched-codes/patchwork/pull/36/files#diff-32d4d49395e98f9a8958fefd0510777e2f157f0c0cbd752fb98ccb485303cbd3)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/PRReview/README.md](https://github.com/patched-codes/patchwork/pull/36/files#diff-0f006562635180059ae21ff8c7a78e33b05ea0532109250429e04f437893a92c)
  [The diff in the README.md file updates the command for running the OpenAI compatible web server using llama.cpp. The new command includes a change in the model from 'deepseek-coder-6.7b-instruct.Q4_0.gguf' to 'deepseek-coder-6.7b-instruct.Q4_K_M.gguf' and adds an additional argument '--chat_format chatml'.](https://github.com/patched-codes/patchwork/pull/36/files#diff-0f006562635180059ae21ff8c7a78e33b05ea0532109250429e04f437893a92c)

</div>

**Review by CTY-git — APPROVED** [review]
LGTM

**Pull request merged**
