### PR TITLE
Add severity and compatibility thresholds

### PR DESCRIPTION
**Pull request by CTY-git**

### CODE REVIEW

**Comment by patched-admin** [comment]
Error log messages for missing configuration and prompt files in a specified directory were changed to warning log messages, with a new message added for the prompt file not being found. In AutoFix.py, an enum class `Compatibility` was introduced with values for different compatibility levels, a method to convert strings to the enum, and error logging for invalid values. The AutoFix class now includes a compatibility threshold attribute, and the `run` method removes responses below the threshold before making code modifications. Additionally, a new value "compatibility: unknown" was added in the "AutoFix Inputs" section, the value "sari_file_path" was updated to "sarif_file_path" in the "defaults.yml" file with the associated comment changed, and ExtractCode.py was modified to include an enumerated type `Severity`, a new function `get_rule_severity`, and modifications to the `transform_sarif_results` function to include a severity threshold parameter.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/33/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [Changed error log messages to warning log messages for missing configuration and prompt files in the specified directory, with a new message added for prompt file being not found.](https://github.com/patched-codes/patchwork/pull/33/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/33/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [The diff introduces an enum class `Compatibility` in AutoFix.py with values representing different compatibility levels, a method to convert a string to the enum, and error logging for invalid values. The AutoFix class is updated to include a compatibility threshold attribute, and within the `run` method, it checks and removes responses below the threshold before proceeding with code modification.](https://github.com/patched-codes/patchwork/pull/33/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/defaults.yml](https://github.com/patched-codes/patchwork/pull/33/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)
  [Added a new value "compatibility: unknown" under the "AutoFix Inputs" section, and updated the value from "sari_file_path" to "sarif_file_path" while changing the associated comment in the "defaults.yml" file.](https://github.com/patched-codes/patchwork/pull/33/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)

</div>

<div markdown="1">

* File changed: [patchwork/steps/ExtractCode/ExtractCode.py](https://github.com/patched-codes/patchwork/pull/33/files#diff-065957bbe7fa12ec637b493e502a0c093c283897108bed8db583c468989a877b)
  [The code in ExtractCode.py was modified to include the addition of an enumerated type `Severity`, a new function `get_rule_severity`, and modifications to the `transform_sarif_results` function to incorporate a severity threshold parameter.](https://github.com/patched-codes/patchwork/pull/33/files#diff-065957bbe7fa12ec637b493e502a0c093c283897108bed8db583c468989a877b)

</div>

**Comment by patched-admin** [comment]
Updates were made to the code in AutoFix.py to include an IntEnum class for compatibility values and a method to convert strings to enums, as well as introducing a compatibility threshold based on user input. A logger was added to handle invalid compatibility values, and responses below the threshold are now filtered out during execution. In defaults.yml, a new field "compatibility" was added while "severity" was removed under "AutoFix Inputs," with a comment update for "sarif_file_path" in the "ExtractCode Inputs" section. The code in ExtractCode.py was modified to include a new Severity class with integer values for severity levels, additional typing hints, and functions to calculate severity based on rules. The function transform_sarif_results now accepts a severity_threshold parameter, and the ExtractCode class constructor now includes a severity_threshold attribute based on user input.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/33/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The code has been updated to change error logs to warnings when the configuration and prompt files are not found in the specified directory, indicating that default configurations and prompts will be used instead.](https://github.com/patched-codes/patchwork/pull/33/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/33/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [The code in AutoFix.py was modified to include an IntEnum class called Compatibility and a method to convert a string value to the corresponding enum value. The AutoFix class was also updated to set a compatibility threshold based on user input and filter out responses below that threshold during execution. Additionally, a logger was introduced to handle invalid compatibility values.](https://github.com/patched-codes/patchwork/pull/33/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/defaults.yml](https://github.com/patched-codes/patchwork/pull/33/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)
  [Added a new field "compatibility" with a value of "unknown" under "AutoFix Inputs," and removed the unused field "severity" while updating a comment about "sarif_file_path" under the "ExtractCode Inputs" section in the defaults.yml file.](https://github.com/patched-codes/patchwork/pull/33/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)

</div>

<div markdown="1">

* File changed: [patchwork/steps/ExtractCode/ExtractCode.py](https://github.com/patched-codes/patchwork/pull/33/files#diff-065957bbe7fa12ec637b493e502a0c093c283897108bed8db583c468989a877b)
  [The code has been modified in ExtractCode.py to include a new class "Severity" with integer values for different levels, additional typing hint, and new functions to calculate severity based on rules. The function transform_sarif_results now accepts a severity_threshold parameter, and the constructor for the class ExtractCode has been updated to include a severity_threshold attribute based on the input.](https://github.com/patched-codes/patchwork/pull/33/files#diff-065957bbe7fa12ec637b493e502a0c093c283897108bed8db583c468989a877b)

</div>

**Review by codelion — APPROVED** [review]
LGTM. So for both compatibility and severity the default it Unknown? And whatever level is set that and above will be processed in the patchflow.

**Comment by patched-admin** [comment]
Multiple code changes were made across various files in the project. In the app.py file, log messages were updated to generate warning messages instead of errors when config or prompt files are not found. The AutoFix.py file was updated to include an Enum class for compatibility levels, a method to convert strings to these values, and a compatibility threshold attribute. The defaults.yml file was updated to add compatibility and severity fields under AutoFix Inputs, and a change was made from "# sari_file_path" to "# sarif_file_path" along with adding a severity field under ExtractCode Inputs. ExtractCode.py was modified to include a Severity class with severity attributes, incorporate a severity threshold in the transform_sarif_results function, and add new imports for Enums and typing at the beginning of the file.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/33/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The code in the patchwork/app.py file has been modified to change the log messages generated when config or prompt files are not found in the specified directory. The logger now generates warning messages instead of error messages, indicating the use of default config or prompt.](https://github.com/patched-codes/patchwork/pull/33/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/33/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [The code in AutoFix.py was updated to include an Enum class `Compatibility`, which assigns integer values to different compatibility levels and a method to convert strings to these values. Additionally, a `compatibility_threshold` attribute was added to the AutoFix class, and a check was implemented during the `run` method to remove patches from responses based on their compatibility level compared to the threshold.](https://github.com/patched-codes/patchwork/pull/33/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/defaults.yml](https://github.com/patched-codes/patchwork/pull/33/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)
  [An update to the defaults.yml file includes adding a compatibility field with a value of "unknown" under AutoFix Inputs, and a change from "# sari_file_path" to "# sarif_file_path" along with adding a severity field with a value of "unknown" under ExtractCode Inputs.](https://github.com/patched-codes/patchwork/pull/33/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)

</div>

<div markdown="1">

* File changed: [patchwork/steps/ExtractCode/ExtractCode.py](https://github.com/patched-codes/patchwork/pull/33/files#diff-065957bbe7fa12ec637b493e502a0c093c283897108bed8db583c468989a877b)
  [The code in ExtractCode.py has been modified to include a Severity class with specific attributes for severity levels and methods for getting severity from a rule. Additionally, there are changes to incorporate a severity threshold in the transform_sarif_results function. New imports for Enums and typing have also been added at the beginning of the file.](https://github.com/patched-codes/patchwork/pull/33/files#diff-065957bbe7fa12ec637b493e502a0c093c283897108bed8db583c468989a877b)

</div>

**Comment by CTY-git** [comment]
yes default is UNKNOWN, which is the lowest level.
and it is a threshold value, only values above it will be not filtered away.

**Pull request merged**
