### PR TITLE
Remove strict git dependency on run

### PR DESCRIPTION
**Pull request by CTY-git**

### CODE REVIEW

**Review by codelion — APPROVED** [review]

**Comment by patched-admin** [comment]
Several changes have been made to the codebase: the addition of an import statement for the 'Any' type in app.py, refactoring the find_module function to find_patchflow for improved handling of modules and classes, updating code related to telemetry and file writing in the cli function, importing the Path class from the pathlib module in patched.py along with modifications to the patched_telemetry method to utilize Path, updating the version of the project in the pyproject.toml file from 0.0.21 to 0.0.22, and adding test fixtures and cases for the patchwork app's command-line interface functionality to test various options and scenarios.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [This patch adds a new import statement for the 'Any' type in the app.py file. It also refactors the find_module function to a new function find_patchflow, which now correctly handles modules and classes when searching for a patchflow. Some code related to handling telemetry and file writing has also been updated in the cli function.](https://github.com/patched-codes/patchwork/pull/236/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/common/client/patched.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)
  [The code in the "patched.py" file has been updated to import the "Path" class from the "pathlib" module. Additionally, changes were made to the "patched_telemetry" method to utilize the "Path" class and handle telemetry inputs differently.](https://github.com/patched-codes/patchwork/pull/236/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/236/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version of the project "patchwork-cli" in the pyproject.toml file has been updated from 0.0.21 to 0.0.22.](https://github.com/patched-codes/patchwork/pull/236/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

<div markdown="1">

* File changed: [tests/common/test_app.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)
  [This diff adds test fixtures and test cases related to the `patchwork` app's command-line interface functionality, including testing default list options, configuration options, CLI success, and failure scenarios. Additionally, tests are added for finding modules based on specific criteria within the application.](https://github.com/patched-codes/patchwork/pull/236/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)

</div>

**Comment by patched-admin** [comment]
The code changes in the patchwork/app.py file involve adding type hinting, refactoring functions, updating error handling and logging messages, and modifying the handling of a patchflow instance. In 'patched.py', an import statement for 'Path' from 'pathlib' is added, 'patched_telemetry' function is modified to use 'Path.cwd()' to create a 'Repo' object, and 'record_patchflow_run' method is called. The project version in pyproject.toml is updated to 0.0.22. Test cases are added to test_app.py, covering scenarios like CLI commands, failures, and module imports with fixtures for setup and testing functions.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The code changes in the patchwork/app.py file involve adding type hinting for a variable, refactoring a function to find a module into two separate functions, updating the error handling and logging messages, and some modifications to the way a patchflow instance is found and handled within the code.](https://github.com/patched-codes/patchwork/pull/236/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/common/client/patched.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)
  [The patch in the 'patched.py' file adds an import statement for 'Path' from the 'pathlib' module. It also modifies the 'patched_telemetry' function to create a 'Repo' object using the current working directory from 'Path.cwd()' instead of passing it as a parameter, before calling 'record_patchflow_run' method.](https://github.com/patched-codes/patchwork/pull/236/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/236/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version of the project in the pyproject.toml file has been updated from 0.0.21 to 0.0.22, while the other fields remain unchanged.](https://github.com/patched-codes/patchwork/pull/236/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

<div markdown="1">

* File changed: [tests/common/test_app.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)
  [This diff adds test cases to the test_app.py file in the project. It includes fixtures for setting up directories and files, test functions for CLI commands, and tests for finding and importing modules within the application. The test cases cover various scenarios like successful CLI commands, failure scenarios, and module import checks.](https://github.com/patched-codes/patchwork/pull/236/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)

</div>

**Comment by patched-admin** [comment]
The code changes involve updating the `app.py` file by importing the `typing` module and renaming the function `find_module` to `find_patchflow`, improving its ability to load and return the specified `patchflow` class from module paths while enhancing error handling and logging. The `patched.py` file now imports the `Path` module from the `pathlib` library, and the `patched_telemetry` method creates a `Repo` object with the current working directory and handles telemetry inputs before recording the patchflow run. Additionally, the project version in the pyproject.toml file has been incremented from 0.0.21 to 0.0.22, and test fixtures and cases have been added to a pytest file to test a command-line tool in Python, creating directories and files for testing and validating the tool's functionality.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The diff in the `app.py` file adds the `typing` module import statement and changes the function `find_module` to `find_patchflow`, updating its implementation to properly load and return the specified `patchflow` class from module paths. Additionally, there are adjustments in error handling and logging related to finding the `patchflow` in module paths.](https://github.com/patched-codes/patchwork/pull/236/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/common/client/patched.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)
  [The diff introduces the import of the `Path` module from the `pathlib` library in the `patched.py` file. Additionally, the `patched_telemetry` method is modified to create a `Repo` object with the current working directory and to handle telemetry inputs before recording the patchflow run.](https://github.com/patched-codes/patchwork/pull/236/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/236/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version of the project in the pyproject.toml file has been updated from 0.0.21 to 0.0.22.](https://github.com/patched-codes/patchwork/pull/236/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

<div markdown="1">

* File changed: [tests/common/test_app.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)
  [This diff includes the addition of test fixtures and test cases in a pytest file for a command-line tool in Python. The fixtures create directories and files for testing, and the test cases validate the functionality of the command-line tool, including checking for successful and failed CLI executions and module imports.](https://github.com/patched-codes/patchwork/pull/236/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)

</div>

**Comment by patched-admin** [comment]
The changes in the code include adding a new import statement for 'typing' at the beginning of the file, refactoring a function to return a sorted list of names, separating the logic for finding patchflows into a different function, improving error handling, adding an import statement for the "Path" class from the "pathlib" module in "patched.py", modifying the parameters of the "patched_telemetry" method to accept a "Path" object instead of a "Repo" object, updating the tool "patchwork-cli" version from 0.0.21 to 0.0.22 in pyproject.toml, and adding test fixtures and functions in the test file "test_app.py" covering various scenarios like running CLI commands with different options and checking function output.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [This patch adds a new import statement for 'typing' in the beginning of the file, and refactors the code by changing a function to return a sorted list of names. Additionally, it modifies the implementation of finding and handling modules within the script by separating the logic for finding patchflows into a different function and improving error handling.](https://github.com/patched-codes/patchwork/pull/236/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/common/client/patched.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)
  [The patch in the file "patched.py" added an import statement for the "Path" class from the "pathlib" module. Additionally, the parameters of the "patched_telemetry" method were modified to accept a "Path" object as the second argument instead of a "Repo" object.](https://github.com/patched-codes/patchwork/pull/236/files#diff-0998e5a615567a2c44e0de84a938c4d225e27ae97018e06f32775aa08db9a091)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/236/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version of the tool "patchwork-cli" in the pyproject.toml file has been updated from 0.0.21 to 0.0.22.](https://github.com/patched-codes/patchwork/pull/236/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

<div markdown="1">

* File changed: [tests/common/test_app.py](https://github.com/patched-codes/patchwork/pull/236/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)
  [This diff file adds test fixtures and test functions to a test file called `test_app.py`. The tests cover various scenarios such as running the CLI command with different options, importing modules, and checking the output of functions.](https://github.com/patched-codes/patchwork/pull/236/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)

</div>

**Pull request merged**
