### PR TITLE
Add gemini support through requests

### PR DESCRIPTION
**Pull request by CTY-git**

### CODE REVIEW

**Comment by patched-admin** [comment]
The code changes involve replacing instances of the function `CallOpenAI` with `CallLLM` in various files and classes within the `patchwork` repository. In `app.py`, the `click.version_option` decorator now includes a `package_name` argument set to `"patchwork-cli"` for version information. New classes such as `CallGemini` and `CallOpenAI` are added for making API calls to language models, and a `CallLLM` class is included for processing prompts based on different API keys. References to `CallOpenAI` in `PRReview.py` and `GenerateREADME.py` have been updated to `CallLLM` for interactions with machine learning models. The `README.md`, `__init__.py`, and `typed.py` files in the `CallLLM` directory do not show any changes.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The diff in the `app.py` file shows a change in the `click.version_option` decorator, where a `package_name` argument with the value `"patchwork-cli"` is added to specify the package name for version information in the command line interface.](https://github.com/patched-codes/patchwork/pull/56/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [This diff in the AutoFix.py file involves changing the CallOpenAI class to CallLLM in two separate instances within the run() method.](https://github.com/patched-codes/patchwork/pull/56/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/DependencyUpgrade.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-e362711d8a271f605d090349067cd24591c174233cd77ccec4b82d5383ca7d86)
  [The identified changes involve replacing instances of the function CallOpenAI with CallLLM within the run method of the DependencyUpgrade class in the DependencyUpgrade.py file. This modification is consistent across three different blocks of code, each involving the replacement of CallOpenAI with CallLLM for carrying out certain operations or tasks within the method.](https://github.com/patched-codes/patchwork/pull/56/files#diff-e362711d8a271f605d090349067cd24591c174233cd77ccec4b82d5383ca7d86)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/GenerateREADME.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-3b7b2ab4b92d52bbebe50698370179ec52882b5ae44f100163bf86f89142de9d)
  [The diff shows a change in the Python script where the CallOpenAI function is replaced with the CallLLM function within the GenerateREADME.py file in the patchflows directory.](https://github.com/patched-codes/patchwork/pull/56/files#diff-3b7b2ab4b92d52bbebe50698370179ec52882b5ae44f100163bf86f89142de9d)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/PRReview/PRReview.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-f57ad4ce8f532cbca9ca77987b7cb0b4424303b47dcd61177c675a64ea0bd693)
  [The code in PRReview.py was changed to replace references to CallOpenAI with CallLLM throughout the file, updating the function calls for interacting with a machine learning model.](https://github.com/patched-codes/patchwork/pull/56/files#diff-f57ad4ce8f532cbca9ca77987b7cb0b4424303b47dcd61177c675a64ea0bd693)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/CallLLM.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-06684f9c0b7bb0e746ea0a10fd6f7cbe2e671ff44a4069e16cdf4faae231c409)
  [This diff adds classes for making API calls to language models, including `CallGemini` and `CallOpenAI`, which inherit from `LLMModel` and contain methods for interacting with the respective models using requests and the OpenAI Python SDK. Additionally, a new class `CallLLM` is added which inherits from `Step` and handles the processing of prompts for the language models, based on different API keys provided in the inputs.](https://github.com/patched-codes/patchwork/pull/56/files#diff-06684f9c0b7bb0e746ea0a10fd6f7cbe2e671ff44a4069e16cdf4faae231c409)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/README.md](https://github.com/patched-codes/patchwork/pull/56/files#diff-b3d23427b81efab5500b31913f224ee178f7922b8cb6b80404395e2a6c7ca62b)
  [There are no changes in the README.md file located in the "CallLLM" directory under patchwork/steps.](https://github.com/patched-codes/patchwork/pull/56/files#diff-b3d23427b81efab5500b31913f224ee178f7922b8cb6b80404395e2a6c7ca62b)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/__init__.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-cec258ecf1ef328b3a1796e3d7dec18f3d7c528a4e715d296085423a4b8e0fd1)
  [No changes were made to the file `__init__.py` in the `CallLLM` module under `patchwork/steps`.](https://github.com/patched-codes/patchwork/pull/56/files#diff-cec258ecf1ef328b3a1796e3d7dec18f3d7c528a4e715d296085423a4b8e0fd1)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/typed.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-7eee5f695e6a689150f65f01187311311ea8560450c433ec8637b6bffbf3795c)
  [There are no changes in the file "typed.py" under the "CallLLM" directory in the patchwork repository.](https://github.com/patched-codes/patchwork/pull/56/files#diff-7eee5f695e6a689150f65f01187311311ea8560450c433ec8637b6bffbf3795c)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallOpenAI/CallOpenAI.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-1a65c740612bf992363dad93d1e86d0579a0015d2294ffa15404cd601972c925)
  [The code snippet is a Python script that defines a class `CallOpenAI` which is a subclass of `Step`. It initializes various attributes and methods for interacting with the OpenAI API, including handling input data, running the model, and saving responses to a JSON file.](https://github.com/patched-codes/patchwork/pull/56/files#diff-1a65c740612bf992363dad93d1e86d0579a0015d2294ffa15404cd601972c925)

</div>

<div markdown="1">

* File changed: [patchwork/steps/__init__.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-f31de71df95e57998018a4108a0780a90d8e790683810803959e17e72412f513)
  [The code has been updated to import and use the module `CallLLM` instead of `CallOpenAI` from the `steps` module within `patchwork`. This change is reflected in the import statements as well as the list of modules in the `__all__` attribute.](https://github.com/patched-codes/patchwork/pull/56/files#diff-f31de71df95e57998018a4108a0780a90d8e790683810803959e17e72412f513)

</div>

**Comment by patched-admin** [comment]
In multiple files within the codebase, the method calls for processing outputs have been updated from `CallOpenAI` to `CallLLM`, indicating a change in the method being used for a specific task. Additionally, the `CallOpenAI` class and related code for interacting with the OpenAI API have been removed from the `CallOpenAI.py` file. The script now relies on the `CallLLM` class for making API calls using different models. In the `__init__.py` file, the reference to `CallOpenAI` has been replaced with `CallLLM` in the `patchwork.steps` module, signaling a shift in the functionality being utilized within the script.

------

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [In the `AutoFix.py` file, the changes include replacing `CallOpenAI` with `CallLLM` in two different instances within the code. This switch indicates a modification in the method being used for processing outputs in the script.](https://github.com/patched-codes/patchwork/pull/56/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/DependencyUpgrade.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-e362711d8a271f605d090349067cd24591c174233cd77ccec4b82d5383ca7d86)
  [The diff in the code snippet shows a change in method calls where `CallOpenAI` is replaced with `CallLLM` in multiple places within the `DependencyUpgrade.py` file. This update affects how certain functions are executed within the script.](https://github.com/patched-codes/patchwork/pull/56/files#diff-e362711d8a271f605d090349067cd24591c174233cd77ccec4b82d5383ca7d86)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/GenerateREADME.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-3b7b2ab4b92d52bbebe50698370179ec52882b5ae44f100163bf86f89142de9d)
  [The diff involves changing a method call from `CallOpenAI` to `CallLLM` in a Python script called `GenerateREADME.py` within the `patchflows` directory. This modification alters the flow of the program by switching the method being used for a specific task.](https://github.com/patched-codes/patchwork/pull/56/files#diff-3b7b2ab4b92d52bbebe50698370179ec52882b5ae44f100163bf86f89142de9d)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/PRReview/PRReview.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-f57ad4ce8f532cbca9ca77987b7cb0b4424303b47dcd61177c675a64ea0bd693)
  [The code in the PRReview.py file was modified to replace the CallOpenAI function calls with CallLLM function calls in several instances, updating the script to use a different function for this action.](https://github.com/patched-codes/patchwork/pull/56/files#diff-f57ad4ce8f532cbca9ca77987b7cb0b4424303b47dcd61177c675a64ea0bd693)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/CallLLM.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-06684f9c0b7bb0e746ea0a10fd6f7cbe2e671ff44a4069e16cdf4faae231c409)
  [The diff shows the addition of classes `CallGemini` and `CallOpenAI` in a Python script `CallLLM.py`, which includes methods for making API calls using different models. The script also includes a `CallLLM` class that makes calls to either `CallGemini` or `CallOpenAI` based on provided API keys, with error handling for missing keys.](https://github.com/patched-codes/patchwork/pull/56/files#diff-06684f9c0b7bb0e746ea0a10fd6f7cbe2e671ff44a4069e16cdf4faae231c409)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/README.md](https://github.com/patched-codes/patchwork/pull/56/files#diff-b3d23427b81efab5500b31913f224ee178f7922b8cb6b80404395e2a6c7ca62b)
  [No changes were made to the "README.md" file in the "CallLLM" step within the "patchwork" directory.](https://github.com/patched-codes/patchwork/pull/56/files#diff-b3d23427b81efab5500b31913f224ee178f7922b8cb6b80404395e2a6c7ca62b)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/__init__.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-cec258ecf1ef328b3a1796e3d7dec18f3d7c528a4e715d296085423a4b8e0fd1)
  [No changes were made in the file `__init__.py` within the `CallLLM` module in the patch.](https://github.com/patched-codes/patchwork/pull/56/files#diff-cec258ecf1ef328b3a1796e3d7dec18f3d7c528a4e715d296085423a4b8e0fd1)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/typed.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-7eee5f695e6a689150f65f01187311311ea8560450c433ec8637b6bffbf3795c)
  [No changes were made to the "typed.py" file in the "CallLLM" directory within the "steps" directory of the patchwork repository.](https://github.com/patched-codes/patchwork/pull/56/files#diff-7eee5f695e6a689150f65f01187311311ea8560450c433ec8637b6bffbf3795c)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallOpenAI/CallOpenAI.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-1a65c740612bf992363dad93d1e86d0579a0015d2294ffa15404cd601972c925)
  [The code in the CallOpenAI class within the CallOpenAI.py file has been removed, including the imports and methods for interacting with the OpenAI API, handling input data, and executing the AI model for generating responses to prompts.](https://github.com/patched-codes/patchwork/pull/56/files#diff-1a65c740612bf992363dad93d1e86d0579a0015d2294ffa15404cd601972c925)

</div>

<div markdown="1">

* File changed: [patchwork/steps/__init__.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-f31de71df95e57998018a4108a0780a90d8e790683810803959e17e72412f513)
  [The code in the `__init__.py` file was updated to import and reference `CallLLM` instead of `CallOpenAI` in the `patchwork.steps` module.](https://github.com/patched-codes/patchwork/pull/56/files#diff-f31de71df95e57998018a4108a0780a90d8e790683810803959e17e72412f513)

</div>

**Review by codelion — APPROVED** [review]

**Comment by patched-admin** [comment]
The code changes involve updating the 'AutoFix' module in the 'patchflows' package to use the new function 'CallLLM' instead of 'CallOpenAI' in the 'run' method and updating the defaults.yml file to require specific API keys for ChatGPT and Gemini while removing model and client base URL properties. Multiple Python files, including DependencyUpgrade.py, GenerateREADME.py, and PRReview.py, have also been modified to replace instances of 'CallOpenAI' with 'CallLLM'. Additionally, a new class 'CallLLM' has been introduced in the `CallLLM.py` file to handle different language models and APIs using prompts specified in a JSON file.

------

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [The code has been updated to make use of a new function 'CallLLM' instead of 'CallOpenAI' within the 'AutoFix' module of the 'patchflows' package. This change is made in the 'run' method where 'CallLLM' is being utilized in place of 'CallOpenAI'.](https://github.com/patched-codes/patchwork/pull/56/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/defaults.yml](https://github.com/patched-codes/patchwork/pull/56/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)
  [The diff in the defaults.yml file involves changes in the CallLLM Inputs section where openai_api_key and google_api_key are designated as required for chatgpt and gemini respectively, and the model and client_base_url properties are commented out in this section.](https://github.com/patched-codes/patchwork/pull/56/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/DependencyUpgrade.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-e362711d8a271f605d090349067cd24591c174233cd77ccec4b82d5383ca7d86)
  [The code in the DependencyUpgrade.py file is being modified to replace instances of "CallOpenAI" with "CallLLM" throughout the file. This change seems to be part of a larger refactoring or functionality update within the script.](https://github.com/patched-codes/patchwork/pull/56/files#diff-e362711d8a271f605d090349067cd24591c174233cd77ccec4b82d5383ca7d86)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/defaults.yml](https://github.com/patched-codes/patchwork/pull/56/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)
  [The diff in the file shows changes to the inputs for OpenAI and Hugging Face models. The OpenAI API key now requires specific keys for different models, such as 'openai_api_key' for ChatGPT and 'google_api_key' for Gemini, while the Hugging Face model has been commented out.](https://github.com/patched-codes/patchwork/pull/56/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/GenerateREADME.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-3b7b2ab4b92d52bbebe50698370179ec52882b5ae44f100163bf86f89142de9d)
  [The code in the GenerateREADME.py file was modified to replace references to CallOpenAI with CallLLM in the script, indicating a change in the function being called for generating responses.](https://github.com/patched-codes/patchwork/pull/56/files#diff-3b7b2ab4b92d52bbebe50698370179ec52882b5ae44f100163bf86f89142de9d)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/defaults.yml](https://github.com/patched-codes/patchwork/pull/56/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)
  [The defaults.yml file has been updated to change the CallOpenAI section to CallLLM, specifying the required API keys for ChatGPT and Gemini, and updating the model and client base URL information while removing the unused model and client base URL for OpenAI.](https://github.com/patched-codes/patchwork/pull/56/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/PRReview/PRReview.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-f57ad4ce8f532cbca9ca77987b7cb0b4424303b47dcd61177c675a64ea0bd693)
  [The changes in the file 'PRReview.py' involve replacing instances of 'CallOpenAI' with 'CallLLM' in the code. This modification includes updating the respective function calls and variables within the 'run' method.](https://github.com/patched-codes/patchwork/pull/56/files#diff-f57ad4ce8f532cbca9ca77987b7cb0b4424303b47dcd61177c675a64ea0bd693)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/PRReview/defaults.yml](https://github.com/patched-codes/patchwork/pull/56/files#diff-979537a26ccecd03e8f803e024fe4771aa5de1928615b388848cf19571d76e5c)
  [The diff in the defaults.yml file removes the CallOpenAI inputs and adds CallLLM inputs for the required keys openai_api_key and google_api_key, as well as specifying the model and client_base_url parameters. Also, an Example HF model is included with the corresponding client_base_url and model details.](https://github.com/patched-codes/patchwork/pull/56/files#diff-979537a26ccecd03e8f803e024fe4771aa5de1928615b388848cf19571d76e5c)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/CallLLM.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-06684f9c0b7bb0e746ea0a10fd6f7cbe2e671ff44a4069e16cdf4faae231c409)
  [This diff introduces new classes for calling language models (LLM) within the `CallLLM.py` file. The classes `CallGemini` and `CallOpenAI` implement the `LLMModel` protocol with methods for making LLM calls using different APIs and handling responses. The `CallLLM` class extends the `Step` class and handles initializing different LLM instances based on input API keys and running the LLM calls using prompts provided in a JSON file.](https://github.com/patched-codes/patchwork/pull/56/files#diff-06684f9c0b7bb0e746ea0a10fd6f7cbe2e671ff44a4069e16cdf4faae231c409)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/README.md](https://github.com/patched-codes/patchwork/pull/56/files#diff-b3d23427b81efab5500b31913f224ee178f7922b8cb6b80404395e2a6c7ca62b)
  [There are no changes in the README.md file located in the CallLLM folder under the patchwork/steps directory.](https://github.com/patched-codes/patchwork/pull/56/files#diff-b3d23427b81efab5500b31913f224ee178f7922b8cb6b80404395e2a6c7ca62b)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/__init__.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-cec258ecf1ef328b3a1796e3d7dec18f3d7c528a4e715d296085423a4b8e0fd1)
  [There were no changes made to the file `__init__.py` in the `CallLLM` module.](https://github.com/patched-codes/patchwork/pull/56/files#diff-cec258ecf1ef328b3a1796e3d7dec18f3d7c528a4e715d296085423a4b8e0fd1)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/typed.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-7eee5f695e6a689150f65f01187311311ea8560450c433ec8637b6bffbf3795c)
  [There were no changes made to the file `typed.py` in the `CallLLM` directory under `patchwork/steps`.](https://github.com/patched-codes/patchwork/pull/56/files#diff-7eee5f695e6a689150f65f01187311311ea8560450c433ec8637b6bffbf3795c)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallOpenAI/CallOpenAI.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-1a65c740612bf992363dad93d1e86d0579a0015d2294ffa15404cd601972c925)
  [The code snippet is from a Python file "CallOpenAI.py" that defines a class called "CallOpenAI" which is a subclass of "Step". It initializes various attributes and methods for interacting with OpenAI, including the processing of JSON prompt files and generating OpenAI responses.](https://github.com/patched-codes/patchwork/pull/56/files#diff-1a65c740612bf992363dad93d1e86d0579a0015d2294ffa15404cd601972c925)

</div>

<div markdown="1">

* File changed: [patchwork/steps/__init__.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-f31de71df95e57998018a4108a0780a90d8e790683810803959e17e72412f513)
  [The import statement from `CallOpenAI` was changed to `CallLLM` in the `__init__.py` file in the `patchwork/steps` directory. Additionally, the variable `CallOpenAI` was updated to `CallLLM` in the `__all__` list.](https://github.com/patched-codes/patchwork/pull/56/files#diff-f31de71df95e57998018a4108a0780a90d8e790683810803959e17e72412f513)

</div>

**Comment by patched-admin** [comment]
Various code changes have been made across different files within the AutoFix module and other directories. References to CallOpenAI have been replaced with CallLLM in multiple sections of files such as defaults.yml, DependencyUpgrade.py, GenerateREADME.py, PRReview.py, and more. The updates involve switching API keys for ChatGPT and Gemini, modifying the model and base URL for OpenAI, and introducing new keys like google_api_key. Additionally, classes like CallGemini and CallOpenAI implementing the LLMModel protocol have been added to handle interactions with different AI models, while the CallOpenAI.py file has been entirely removed. The README generator file has also been updated to accommodate these changes.

------

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [The code in the AutoFix module has been updated to replace a reference to CallOpenAI with CallLLM in two different sections of the file.](https://github.com/patched-codes/patchwork/pull/56/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/defaults.yml](https://github.com/patched-codes/patchwork/pull/56/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)
  [The diff in the file defaults.yml within the AutoFix directory of the patchflows folder involves changing CallOpenAI Inputs to CallLLM Inputs, updating the required API keys for ChatGPT and Gemini, and modifying the model and base URL for OpenAI.](https://github.com/patched-codes/patchwork/pull/56/files#diff-a3fa1a5b6f90cd078a8e53ea1a6eee06e8a195cfa3adc04e62df5be9de15a587)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/DependencyUpgrade.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-e362711d8a271f605d090349067cd24591c174233cd77ccec4b82d5383ca7d86)
  [The diff in the DependencyUpgrade.py file involves replacing instances of CallOpenAI with CallLLM throughout the script. This change modifies the function calls used for running a specific task in the script.](https://github.com/patched-codes/patchwork/pull/56/files#diff-e362711d8a271f605d090349067cd24591c174233cd77ccec4b82d5383ca7d86)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/DependencyUpgrade/defaults.yml](https://github.com/patched-codes/patchwork/pull/56/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)
  [The diff shows changes in the defaults.yml file related to APIs for OpenAI and Google. The CallOpenAI inputs are replaced with CallLLM inputs and new keys like google_api_key are added, while some existing ones like model and client_base_url remain unchanged.](https://github.com/patched-codes/patchwork/pull/56/files#diff-1fdd0d2ab29a0ce2905ee48194d70f19e830ef0fa3e1a029d7359a2374e55583)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/GenerateREADME.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-3b7b2ab4b92d52bbebe50698370179ec52882b5ae44f100163bf86f89142de9d)
  [The file GenerateREADME.py in the patchflows directory of the patchwork repository has been modified to replace a CallOpenAI function with a CallLLM function throughout the file.](https://github.com/patched-codes/patchwork/pull/56/files#diff-3b7b2ab4b92d52bbebe50698370179ec52882b5ae44f100163bf86f89142de9d)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateREADME/defaults.yml](https://github.com/patched-codes/patchwork/pull/56/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)
  [The default configuration in the README generator file has been updated to include CallLLM inputs for the OpenAI and Google API keys, with new required keys for ChatGPT and Gemini, and the removal of the GPT model designation.](https://github.com/patched-codes/patchwork/pull/56/files#diff-c5035e7988d84c7943fc075b5d95891f71b965704c91943afe14302676f91d68)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/PRReview/PRReview.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-f57ad4ce8f532cbca9ca77987b7cb0b4424303b47dcd61177c675a64ea0bd693)
  [The file PRReview.py is being modified to replace the use of CallOpenAI with CallLLM in the run method, implying a change from using the OpenAI API to possibly a different API or service for the specific function being performed.](https://github.com/patched-codes/patchwork/pull/56/files#diff-f57ad4ce8f532cbca9ca77987b7cb0b4424303b47dcd61177c675a64ea0bd693)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/PRReview/defaults.yml](https://github.com/patched-codes/patchwork/pull/56/files#diff-979537a26ccecd03e8f803e024fe4771aa5de1928615b388848cf19571d76e5c)
  [The OpenAI API key requirement has been revised and split into two different keys, one for ChatGPT and one for Gemini. The model and client base URL configuration for CallLLM have also been added, while comments for the CallOpenAI inputs have been removed.](https://github.com/patched-codes/patchwork/pull/56/files#diff-979537a26ccecd03e8f803e024fe4771aa5de1928615b388848cf19571d76e5c)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/CallLLM.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-06684f9c0b7bb0e746ea0a10fd6f7cbe2e671ff44a4069e16cdf4faae231c409)
  [The diff adds new classes `CallGemini` and `CallOpenAI` that implement the `LLMModel` protocol for interacting with different AI models. The `CallLLM` class is updated to handle different model selections and calls to various AI models based on input API keys.](https://github.com/patched-codes/patchwork/pull/56/files#diff-06684f9c0b7bb0e746ea0a10fd6f7cbe2e671ff44a4069e16cdf4faae231c409)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/README.md](https://github.com/patched-codes/patchwork/pull/56/files#diff-b3d23427b81efab5500b31913f224ee178f7922b8cb6b80404395e2a6c7ca62b)
  [There are no changes in the README.md file under the "patchwork/steps/CallLLM" directory.](https://github.com/patched-codes/patchwork/pull/56/files#diff-b3d23427b81efab5500b31913f224ee178f7922b8cb6b80404395e2a6c7ca62b)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/__init__.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-cec258ecf1ef328b3a1796e3d7dec18f3d7c528a4e715d296085423a4b8e0fd1)
  [There are no changes in the file `__init__.py` in the `CallLLM` directory under `patchwork/steps`.](https://github.com/patched-codes/patchwork/pull/56/files#diff-cec258ecf1ef328b3a1796e3d7dec18f3d7c528a4e715d296085423a4b8e0fd1)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallLLM/typed.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-7eee5f695e6a689150f65f01187311311ea8560450c433ec8637b6bffbf3795c)
  [In the "typed.py" file within the "CallLLM" module, a new field "google_api_key" of type string has been added to the "CallOpenAIInputs" TypedDict class.](https://github.com/patched-codes/patchwork/pull/56/files#diff-7eee5f695e6a689150f65f01187311311ea8560450c433ec8637b6bffbf3795c)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallOpenAI/CallOpenAI.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-1a65c740612bf992363dad93d1e86d0579a0015d2294ffa15404cd601972c925)
  [The file "CallOpenAI.py" has been entirely removed in the patch without any replacements or modifications. The class "CallOpenAI" with methods for API interactions and data handling has been completely removed from the code base.](https://github.com/patched-codes/patchwork/pull/56/files#diff-1a65c740612bf992363dad93d1e86d0579a0015d2294ffa15404cd601972c925)

</div>

<div markdown="1">

* File changed: [patchwork/steps/__init__.py](https://github.com/patched-codes/patchwork/pull/56/files#diff-f31de71df95e57998018a4108a0780a90d8e790683810803959e17e72412f513)
  [The code in the `__init__.py` file is being updated to import and reference a module named `CallLLM` instead of `CallOpenAI`. The changes affect the module imports and the items included in the `__all__` list.](https://github.com/patched-codes/patchwork/pull/56/files#diff-f31de71df95e57998018a4108a0780a90d8e790683810803959e17e72412f513)

</div>

**Pull request merged**
