### PR TITLE
Remove `chromadb` imports in utils

### PR DESCRIPTION
**Pull request by CTY-git**

### CODE REVIEW

**Comment by patched-admin** [comment]
The code change in the utils.py file updates import statements to use the dependency module instead of directly importing from chromadb, changing references to embedding_functions with paths using dependency. The return types of the functions openai_embedding_model and huggingface_embedding_model are adjusted to match the new import structure.

------

<div markdown="1">

* File changed: [patchwork/common/utils/utils.py](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)
  [The diff in the utils.py file updates the import statements to utilize the dependency module instead of directly importing from chromadb, replacing references to embedding_functions with paths using dependency. Additionally, the functions openai_embedding_model and huggingface_embedding_model have their return types adjusted to match the new import structure.](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)

</div>

**Comment by patched-admin** [comment]
The test.yml GitHub Actions workflow file change introduces new jobs for security, file issue testing, and general testing with specific steps like Python setup, Poetry installation, cached environments loading, and running commands for testing and issue resolution. In utils.py, changes involve importing modules from chromadb, updating import statements and function definitions to use the chromadb module, adjusting EmbeddingFunction types to refer to ones from chromadb.api.types, and updating methods in functions like openai_embedding_model and huggingface_embedding_model to utilize chromadb.utils.embedding_functions.

------

<div markdown="1">

* File changed: [.github/workflows/test.yml](https://github.com/patched-codes/patchwork/pull/224/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)
  [This diff in the test.yml GitHub Actions workflow file adds new jobs for security testing, testing relevant files for issues, and overall testing, each with specific steps like setting up Python, installing Poetry, loading cached virtual environments, and running specific commands for testing and issue resolution.](https://github.com/patched-codes/patchwork/pull/224/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)

</div>

<div markdown="1">

* File changed: [patchwork/common/utils/utils.py](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)
  [The diff in the utils.py file involves changes related to importing modules from chromadb, specifically updating the import statements and function definitions to use the `chromadb` module. Additionally, the `EmbeddingFunction` types are updated to reference the ones from the `chromadb.api.types` module, and functions like `openai_embedding_model` and `huggingface_embedding_model` now utilize methods from `chromadb.utils.embedding_functions`.](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)

</div>

**Comment by patched-admin** [comment]
In the GitHub workflow file test.yml, new jobs "security-test" and "rag-test" are added with steps to set up Python, install dependencies, and run security or specific tests. Another new job "main-test" is included to review pull requests. In utils.py, import statements are adjusted to include chromadb modules, function return types are updated to reference chromadb types, and function instantiation is changed to use methods from chromadb.utils.embedding_functions.

------

<div markdown="1">

* File changed: [.github/workflows/test.yml](https://github.com/patched-codes/patchwork/pull/224/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)
  [The diff in the GitHub workflow file test.yml adds two new jobs, "security-test" and "rag-test", each with steps to set up Python, install dependencies, and run specific tests related to security or a specific issue. Additionally, a new job "main-test" is added to install dependencies and review a pull request.](https://github.com/patched-codes/patchwork/pull/224/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)

</div>

<div markdown="1">

* File changed: [patchwork/common/utils/utils.py](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)
  [The diff in `utils.py` modifies import statements to include `chromadb` modules, changes the return types of functions to reference `chromadb` types in signatures, and updates the instantiation of functions to use methods from `chromadb.utils.embedding_functions` instead of `embedding_functions`.](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)

</div>

**Review by codelion — APPROVED** [review]

**Comment by patched-admin** [comment]
The code changes in the workflow file `test.yml` add new job types for `generatedocstring`, `security-test`, `rag-test`, and `main-test`, each with specific steps related to setting up Python, installing dependencies, and running tests. Import statements related to "chromadb" and "embedding_functions" are removed and replaced with imports from a new module "chromadb" within the "dependency" sub-module of "utils". Function signatures for certain functions are updated to use the new imports. Additionally, the version of the project in the pyproject.toml file has been updated from 0.0.19 to 0.0.20.

------

<div markdown="1">

* File changed: [.github/workflows/test.yml](https://github.com/patched-codes/patchwork/pull/224/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)
  [The diff includes changes in the workflow file `test.yml`, where new job types `generatedocstring`, `security-test`, `rag-test`, and `main-test` are added, each with specific steps like setting up Python, installing dependencies, and running tests related to security, patchwork, and main tests with different code checks and actions triggered on specific events.](https://github.com/patched-codes/patchwork/pull/224/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)

</div>

<div markdown="1">

* File changed: [patchwork/common/utils/utils.py](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)
  [The diff removes imports related to "chromadb" and "embedding_functions" from the top of the file and from specific functions, replacing them with imports from a new module "chromadb" within the "dependency" sub-module of "utils". Function signatures for "openai_embedding_model", "huggingface_embedding_model", and "get_embedding_function" are updated to use the new imports "chromadb" for the respective types and classes. The "_EMBEDDING_TO_API_KEY_NAME" dictionary is modified to use updated type annotations for the function definitions.](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/224/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version of the project in the pyproject.toml file has been updated from 0.0.19 to 0.0.20.](https://github.com/patched-codes/patchwork/pull/224/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

**Comment by patched-admin** [comment]
The code changes include adding new jobs for security and regression testing in the GitHub workflow file, updating cache keys for the virtual environment, and adding steps to propose relevant files to issues. The README.md file change switches from using double quotes to single quotes in the installation command for PatchWork. In the utils.py file, imports are changed to a new location and functions are modified for 'embedding_functions.' Lastly, the version for "patchwork-cli" in the pyproject.toml file is updated from 0.0.19 to 0.0.20.

------

<div markdown="1">

* File changed: [.github/workflows/test.yml](https://github.com/patched-codes/patchwork/pull/224/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)
  [The diff in the GitHub workflow file adds two new jobs for security testing and regression testing, each with their respective steps such as setting up Python, installing dependencies, and running specific tests or tasks. The cache keys for loading the virtual environment are updated to include the job context, and additional steps are added for proposing relevant files to issues in the codebase as part of the testing process.](https://github.com/patched-codes/patchwork/pull/224/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)

</div>

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/224/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  [The diff in the README.md file shows a change in the installation command for PatchWork from using double quotes to using single quotes around 'patchwork-cli[all]' to improve compatibility and avoid interpretation issues during installation.](https://github.com/patched-codes/patchwork/pull/224/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

</div>

<div markdown="1">

* File changed: [patchwork/common/utils/utils.py](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)
  [The patch changes the import statements in the utils.py file to import from a different location, 'patchwork.common.utils.dependency.chromadb,' instead of the previous location. Additionally, the functions 'openai_embedding_model' and 'huggingface_embedding_model' are modified to use the new import location for 'embedding_functions.'](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/224/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version in the pyproject.toml file for the "patchwork-cli" tool has been updated from 0.0.19 to 0.0.20.](https://github.com/patched-codes/patchwork/pull/224/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

**Comment by patched-admin** [comment]
The code changes involve updating the workflow file to include new jobs such as "generatedocstring-*", "security-test", "rag-test", and "main-test". Additionally, there are new optional dependency groups available for PatchWork, instructions for installing them using pip, and details on installing PatchWork using Poetry. Import statements and function signatures in utils.py have been modified to use local dependency modules, specifically for chromadb. Finally, the version in the pyproject.toml file for "patchwork-cli" has been incremented from 0.0.19 to 0.0.20.

------

<div markdown="1">

* File changed: [.github/workflows/test.yml](https://github.com/patched-codes/patchwork/pull/224/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)
  [The workflow file ".github/workflows/test.yml" was updated to include a new job called "generatedocstring-*" and restructured the existing jobs. The changes also involve adding a new job "security-test" for running security tests, a "rag-test" job for proposing relevant files to specific issues, and a "main-test" job for general testing purposes.](https://github.com/patched-codes/patchwork/pull/224/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)

</div>

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/224/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  [The diff adds information about optional dependency groups available for PatchWork, including `security`, `rag`, and `all`, with specific instructions on how to install them using pip for different patchflows. Additional details are also provided for installing PatchWork using Poetry to build from source.](https://github.com/patched-codes/patchwork/pull/224/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

</div>

<div markdown="1">

* File changed: [patchwork/common/utils/utils.py](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)
  [The diff introduces changes to import statements and function signatures in the utils.py file. It replaces imports related to chromadb with an import from a local dependency module, "patchwork.common.utils.dependency.chromadb". The functions openai_embedding_model, huggingface_embedding_model, and get_embedding_function have updated function signatures referring to chromadb modules.](https://github.com/patched-codes/patchwork/pull/224/files#diff-f3466dc43f091cee836042d9954f12a719cf38d5ede82bd0ad66fd68095f0ab3)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/224/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version in the `pyproject.toml` file for the project "patchwork-cli" has been updated from 0.0.19 to 0.0.20.](https://github.com/patched-codes/patchwork/pull/224/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

**Pull request merged**
