### PR TITLE
Update README.md, disable telemetry on tests

### PR DESCRIPTION
**Pull request by codelion**
Disable telemetry on tests.

### CODE REVIEW

**Comment by patched-admin** [comment]
The README.md file has been modified to update the list of predefined patchflows in Patchwork by linking each item to a specific path within the patchflows directory. Brackets and paths have been added for each patchflow item, providing a more specific indication of where to locate each feature within the repository.

------

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/279/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  [The diff in the README.md file updates the list of predefined patchflows in Patchwork by linking each item to a specific path within the patchflows directory. The changes include adding brackets and paths for each patchflow item, making it more specific on where to find each feature in the repository.](https://github.com/patched-codes/patchwork/pull/279/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

</div>

**Comment by patched-admin** [comment]
The README.md file was modified to add clickable links to each patchflow item in the patchflows section. Furthermore, the roadmap section was updated by removing specific quarters (Q2 '24 and Q3/Q4 '24) from the short-term and long-term milestones and instead making them more generalized as Short Term and Long Term milestones.

------

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/279/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  [The diff in the README.md file updates the patchflows section by adding clickable links to each patchflow item. Additionally, the roadmap section is modified by removing specific quarters (Q2 '24 and Q3/Q4 '24) from the short-term and long-term milestones and making them more general (Short Term and Long Term).](https://github.com/patched-codes/patchwork/pull/279/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

</div>

**Comment by patched-admin** [comment]
In the README.md file, hyperlinks are added to each patchflow's name in the patchflows section, along with their respective paths. The timeframes in the roadmap section are adjusted from specific quarters to more general terms like Short Term and Long Term. In the patchwork/app.py file, the default value setting for the "--disable-telemetry" flag in the click.option is removed.

------

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/279/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  [The diff in the README.md file updates the patchflows section by adding hyperlinks to each patchflow's name, indicating their respective paths. Additionally, the roadmap section's timeframes are adjusted from specific quarters ('Q2 '24, Q3/Q4 '24) to more general terms like Short Term and Long Term.](https://github.com/patched-codes/patchwork/pull/279/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

</div>

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/279/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The diff in the given patchwork/app.py file updates the click.option for the "--disable-telemetry" flag by removing the default value setting in the code.](https://github.com/patched-codes/patchwork/pull/279/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

**Comment by patched-admin** [comment]
The code changes involve adding a "--disable_telemetry" flag to commands in the GitHub Actions workflow file for various tasks, updating the README.md file to include links to predefined patchflows and simplifying timeline information, and modifying the default value and label of the click option for disabling telemetry in the app.py file.

------

<div markdown="1">

* File changed: [.github/workflows/test.yml](https://github.com/patched-codes/patchwork/pull/279/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)
  [The changes in the GitHub Actions workflow file include adding a "--disable_telemetry" flag to commands in multiple steps for different jobs to disable telemetry information reporting during various tasks such as generating PRs, resolving issues, and generating documentation and READMEs.](https://github.com/patched-codes/patchwork/pull/279/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)

</div>

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/279/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  [The diff in the README.md file updates the list of predefined patchflows by adding links to each patchflow name and modifies the timeline information from "Short Term Q2 '24" and "Long Term Q3/Q4 '24" to simply "Short Term" and "Long Term," respectively.](https://github.com/patched-codes/patchwork/pull/279/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

</div>

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/279/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [In the app.py file, a click option for disabling telemetry was modified to have a default value of False and is now correctly labeled as "--disable_telemetry".](https://github.com/patched-codes/patchwork/pull/279/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

**Comment by patched-admin** [comment]
In the code changes, the GitHub workflow test.yml file now includes the option "--disable_telemetry" in various commands for patchwork processes to prevent telemetry data collection. The README.md file adds a new optional dependency group for notifications and updates the patchflows list with specific links. The `click.option` decorator remains unchanged with the `--disable-telemetry` option and a default value of `False`.

------

<div markdown="1">

* File changed: [.github/workflows/test.yml](https://github.com/patched-codes/patchwork/pull/279/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)
  [The diff in the GitHub workflow test.yml file adds the option "--disable_telemetry" in various commands for patchwork processes to disable telemetry. This option is added to commands in actions related to AutoFix, Dependency Upgrade, ResolveIssue, PRReview, GenerateDocstring, and Generate README to prevent telemetry data collection.](https://github.com/patched-codes/patchwork/pull/279/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)

</div>

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/279/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  [The diff in the README.md file adds a new optional dependency group named "notifications" for sending notifications, such as Slack messages during certain steps. Additionally, the diff updates the patchflows list with links to specific patchflows like GenerateDocstring and AutoFix, and adjusts the roadmap sections to remove specific quarters and instead use broader timeframes (Short Term and Long Term).](https://github.com/patched-codes/patchwork/pull/279/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

</div>

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/279/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The diff shows a change in the `click.option` decorator where `--disable-telemetry` option was initially named as `--disable-telemetry` and had a default value of `False`, and this value remains unchanged even after the modification in the code.](https://github.com/patched-codes/patchwork/pull/279/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

**Review by CTY-git — APPROVED** [review]

**Pull request merged**
