### PR TITLE
Update GenerateDocstring.py

### PR DESCRIPTION
**Pull request by codelion**

### CODE REVIEW

**Comment by patched-admin** [comment]
A conditional check has been added to the code to set a key in the 'final_inputs' dictionary. The check verifies that the key "force_code_contexts" is not present and that "rewrite_existing" is present before assigning the value of 'rewrite_existing' to 'force_code_contexts'.

------

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateDocstring/GenerateDocstring.py](https://github.com/patched-codes/patchwork/pull/193/files#diff-a39a765ae3b1b6cf23ad938684021d695ca8b06097ec9e6e374689ad0622641a)
  [In this code diff, a new conditional check has been added to set a key in the 'final_inputs' dictionary. It checks for the absence of the key "force_code_contexts" and the presence of the key "rewrite_existing" before assigning the value of 'rewrite_existing' to 'force_code_contexts'.](https://github.com/patched-codes/patchwork/pull/193/files#diff-a39a765ae3b1b6cf23ad938684021d695ca8b06097ec9e6e374689ad0622641a)

</div>

**Comment by patched-admin** [comment]
A new key "force_code_contexts" has been added to the dictionary "final_inputs" in the code change, where the value is fetched from the existing key "rewrite_existing" and set to False if "rewrite_existing" is not present. Additionally, the defaults.yml file in the patchflows directory has been updated to include a new parameter 'rewrite_existing' with a value of false for the 'GenerateDocstring Inputs' section.

------

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateDocstring/GenerateDocstring.py](https://github.com/patched-codes/patchwork/pull/193/files#diff-a39a765ae3b1b6cf23ad938684021d695ca8b06097ec9e6e374689ad0622641a)
  [In this code change, a new key "force_code_contexts" is added to the dictionary "final_inputs" with a value fetched from the existing key "rewrite_existing" and set to False if "rewrite_existing" is not present.](https://github.com/patched-codes/patchwork/pull/193/files#diff-a39a765ae3b1b6cf23ad938684021d695ca8b06097ec9e6e374689ad0622641a)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateDocstring/defaults.yml](https://github.com/patched-codes/patchwork/pull/193/files#diff-f455b51e69786e7ffafee99e552b81b0d672df1ff9ac39a448f1a9663da4fbdf)
  [The defaults.yml file in the patchflows directory has been modified by adding a new parameter 'rewrite_existing' with a value of false for the 'GenerateDocstring Inputs' section.](https://github.com/patched-codes/patchwork/pull/193/files#diff-f455b51e69786e7ffafee99e552b81b0d672df1ff9ac39a448f1a9663da4fbdf)

</div>

**Comment by patched-admin** [comment]
The code changes involve adding new variables in the ignore.py file to store file extensions and filenames to be ignored using globs, updating the is_ignored function to use these variables, and allowing additional globs and directories to be ignored as arguments. In GenerateDocstring class, a new key "force_code_contexts" is added to the final_inputs dictionary with a value based on the presence of "rewrite_existing". In defaults.yml, a new parameter "rewrite_existing" with a default value of false is added for generating docstrings. Import statements in ExtractCodeContexts.py have been modified to import the is_ignored function instead of using specific variables, and the code within the os.walk loop has been simplified to utilize is_ignored to determine file inclusion.

------

<div markdown="1">

* File changed: [patchwork/common/ignore.py](https://github.com/patched-codes/patchwork/pull/193/files#diff-f401e1b35e883626b703d5dcdc70adb2813fd323e441c5f496bf6152300d1e30)
  [This diff in the `ignore.py` file adds new variables to store file extensions and filenames to be ignored using globs. It also updates the `is_ignored` function to use the newly added variables and allows passing additional globs and directories to be ignored as arguments to the function.](https://github.com/patched-codes/patchwork/pull/193/files#diff-f401e1b35e883626b703d5dcdc70adb2813fd323e441c5f496bf6152300d1e30)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateDocstring/GenerateDocstring.py](https://github.com/patched-codes/patchwork/pull/193/files#diff-a39a765ae3b1b6cf23ad938684021d695ca8b06097ec9e6e374689ad0622641a)
  [A new key `"force_code_contexts"` is added to the `final_inputs` dictionary in the `__init__` method of the `GenerateDocstring` class with a value retrieved from `final_inputs["rewrite_existing"]` or `False` if the key is not present.](https://github.com/patched-codes/patchwork/pull/193/files#diff-a39a765ae3b1b6cf23ad938684021d695ca8b06097ec9e6e374689ad0622641a)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/GenerateDocstring/defaults.yml](https://github.com/patched-codes/patchwork/pull/193/files#diff-f455b51e69786e7ffafee99e552b81b0d672df1ff9ac39a448f1a9663da4fbdf)
  [In the `defaults.yml` file in the `GenerateDocstring` section of the code, a new parameter `rewrite_existing` with a value of `false` has been added to the inputs for generating docstrings.](https://github.com/patched-codes/patchwork/pull/193/files#diff-f455b51e69786e7ffafee99e552b81b0d672df1ff9ac39a448f1a9663da4fbdf)

</div>

<div markdown="1">

* File changed: [patchwork/steps/ExtractCodeContexts/ExtractCodeContexts.py](https://github.com/patched-codes/patchwork/pull/193/files#diff-e2a1b000d3fad705cecda7fa5a37c46669f73d0d3aae33751d30388814d50924)
  [In the file ExtractCodeContexts.py, the import statements have been modified to import the function is_ignored from patchwork.common.ignore instead of importing IGNORE_DIRS and IGNORE_EXTS. The code within the os.walk loop has also been simplified to use the is_ignored function on file paths for checking if a file should be considered.](https://github.com/patched-codes/patchwork/pull/193/files#diff-e2a1b000d3fad705cecda7fa5a37c46669f73d0d3aae33751d30388814d50924)

</div>

**Comment by codelion** [comment]
Looks good let’s merge

**Review by CTY-git — APPROVED** [review]

**Pull request merged**
