### PR TITLE
Add azure devops PR related implementations

### PR DESCRIPTION
**Pull request by CTY-git**
## PR Checklist

- [x] The commit message follows our guidelines: [Code of conduct](https://github.com/patched-codes/patchwork/blob/main/CODE_OF_CONDUCT.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Does this PR introduce a breaking change?
- [x] Include PR in release notes?

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Build /CI
- [ ] Documentation
- [ ] Others

## What is the current behavior?
Azure Devops can only create PRs

Issue Number: #999

## What is the new behavior?

Azure Devops can create PRs and create comments.

## Other information

### CODE REVIEW

**Comment by patched-admin** [comment]
The pull request review addresses several aspects of the code changes, highlighting potential bugs, security vulnerabilities, and adherence to coding standards. A primary concern is a missing import for the `Comment` class, which could lead to runtime errors, and potential `AttributeError` in the `texts` method due to null checks not being implemented for `diff.a_blob` or `diff.b_blob`. Regarding security, the visibility of a sensitive token in the main execution section poses a risk and should be managed using secure practices such as environment variables. Additionally, error logging could inadvertently reveal sensitive information, and custom exception handling was suggested for better control. The proposed version bump in `pyproject.toml` does not introduce direct issues, but testing associated dependencies is recommended to prevent indirect problems. An update introduces a new enum option `GenerateCodeUsageExample`, necessitating checks to ensure it doesn't disrupt existing functionality and adhere to security standards. Overall, the review suggests that while the changes are structurally appropriate, addressing these observations will enhance the application's security and reliability.

------

<div markdown="1">

* File changed: [patchwork/common/client/scm.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-a4a0213f577e66fc33444faad6c1991a8c60deb8fc7d5b5527069a66f59804f5)
  1. **Potential Bugs**:
   - The `create_comment` method is attempting to create a `Comment` object without importing `Comment` from a module. This could potentially cause a bug if `Comment` is not available in the current scope, especially since the previous `Comment` class definition was removed from this file.
   - In the `texts` method, while using `unified_diff`, if the `diff.a_blob` or `diff.b_blob` is `None`, attempting to access the `data_stream` could lead to an `AttributeError`. A check should be added to ensure `a_blob` and `b_blob` are not `None` before trying to read them.

2. **Security Vulnerabilities**:
   - The token `EZ1PAM0W9v0nUZhmgjeTvaUFp9xcCiXTot0ImFdyQg96D1YgCKdCJQQJ99ALACAAAAAAAAAAAAASAZDONH1a` is visible in the main execution section. This should be replaced with a secure way of managing secrets, like environment variables or secret management tools, to prevent accidental disclosure.
   - Logging errors directly can inadvertently expose sensitive information. This is evident in methods where exceptions are logged with `logger.error(e)`. If `e` contains sensitive data, it could appear in logs.

3. **Coding Standards**:
   - The type hinting and naming conventions seem consistent but there is some inconsistency in exception handling. Consider using custom exception classes for better granularity and control over exception handling.
   - The removal of `class Comment` previously defined with `@define` suggests a move towards relying on imported `Comment` objects, which should be checked for compatibility and correctness in construction across the rest of the code.
   - The `find_pr_by_id` should consistently return a type that matches its expected return type across different SCM platforms (i.e., `GithubPullRequest`, `GitlabMergeRequest`, `AzureDevopsPullRequest`). Ensure each method follows this convention strictly. 

The code seems to align with the general structural adjustments being made, but these changes, especially involving tokens and exception handling, should be addressed to enhance security and reliability.

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/1142/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  The pull request only involves a version bump in the `pyproject.toml` file from `0.0.85` to `0.0.86`. Since there are no code changes beyond this version update, there are no potential bugs introduced in the source code. Additionally, no security vulnerabilities are directly introduced by changing the version number. The file adheres to standard TOML formatting and there is no deviation from original coding standards apparent in this change. However, it's important to ensure that any dependencies or code associated with this version bump have been thoroughly tested to avoid indirect issues.

</div>

<div markdown="1">

* File changed: [tests/common/test_app.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)
  The code modifications add a new enum option `GenerateCodeUsageExample` to the list of default and config list options. Here are some considerations:

1. **Potential Bugs**: 
   - Ensure that the addition of the `GenerateCodeUsageExample` option does not break existing functionality. The test cases appear to be updated appropriately, but it should be verified that this option is supported throughout the application where these test methods might be used.

2. **Security Vulnerabilities**:
   - Adding new functionality (even in test cases) can introduce security vulnerabilities if not handled properly. Ensure that `GenerateCodeUsageExample` is not leading to any paths where untrusted input could be executed or misused.

3. **Coding Standards**:
   - The addition appears to follow the existing coding standards by adding the new option in the same style as others. It maintains the alignment and formatting conventions observed in the rest of the code snippet.

Further review of the surrounding context and how these test cases integrate with the production code would be helpful to provide a comprehensive review.

</div>

**Comment by patched-admin** [comment]
The pull request review addresses several concerns regarding potential bugs, security vulnerabilities, and coding standards. In the potential bugs section, it highlights that the ambiguous use of the `Comment` class in `create_comment` could lead to runtime errors due to a recent implementation change, while `get_slug_and_id_from_url` lacks error handling and validation, risking `NoneType` errors or `ValueError`s. Security issues arise from direct string interpolation in logs, potentially exposing sensitive data, and hardcoded credentials in the main script, recommending the use of environment variables. Coding standards could be enhanced with more inline comments for clarity, and consistent tuple unpacking styling. The primary change involves updating `patchwork-cli`'s version number, with no potential bugs or security vulnerabilities introduced. Updates in the `tests/common/test_app.py` file suggest modifications to test expectations, notably regarding `GenerateCodeUsageExample`, but emphasize the importance of running tests post-merge for compatibility with application logic.

------

<div markdown="1">

* File changed: [patchwork/common/client/scm.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-a4a0213f577e66fc33444faad6c1991a8c60deb8fc7d5b5527069a66f59804f5)
  1. **Potential Bugs:**
   - In `create_comment`, the variable `Comment` is ambiguously used. The previous custom `Comment` class has been removed, and now there is an imported `Comment` class from `azure.devops.v7_1.git.models`. It's not clear whether the new import is meant to replace the previous implementation. This could lead to runtime errors if the imported `Comment` class doesn't match the intended structure.
   - The function `get_slug_and_id_from_url` returns `None` if the URL parsing fails, but no further error handling is done for cases where this function is called and can return `None`. This can lead to `TypeError`s or `ValueError`s if not appropriately handled when unpacking the expected tuple.
   - There's potential for `ValueError` not being caught in functions like `get_slug_and_id_from_url` where integer parsing is being done from the URL path. This should be handled within a try-except block or handled by validating the URL format before attempting to parse.

2. **Security Vulnerabilities:**
   - Direct string interpolation in log messages (e.g., `logger.error(f"Invalid URL: {url}")`) without sanitization might log sensitive data if the URL contains tokens or credentials. Consider sanitizing or obfuscating the URL content.
   - The main script under `if __name__ == "__main__":` contains hardcoded credentials (`"EZ1PAM0W9v0nUZhmgjeTvaUFp9xcCiXTot0ImFdyQg96D1YgCKdCJQQJ99ALACAAAAAAAAAAAAASAZDONH1a"`). This should be replaced with environment variables or secured configuration management to avoid exposing secrets in the codebase.

3. **Coding Standards:**
   - Usage of inline comments could improve understanding, especially in more complex function implementations like `texts`. Consider adding comments to explain non-trivial code blocks.
   - The usage of unpacking and destructuring tuples should be consistent with the existing codebase styling. Inconsistent usage may cause confusion among developers familiar with the original style.
   - The removal of the `@define` `Comment` class without documented inline comments on the purpose may lead to confusion about refactoring decisions.

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/1142/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  The change in this pull request modifies only the version number of the `patchwork-cli` package from `0.0.85` to `0.0.86` in the `pyproject.toml` file. 

Potential Bugs:
- There are no potential bugs introduced as it is just a version number change.

Security Vulnerabilities:
- This modification does not introduce any new security vulnerabilities as no code execution related changes are made.

Coding Standards:
- The modification adheres to the original coding standards, assuming consistent use of semantic versioning as likely indicated by the increment of the patch version number.

</div>

<div markdown="1">

* File changed: [tests/common/test_app.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)
  The current changes in the `tests/common/test_app.py` file appear to be straightforward updates to test cases, with the addition of a new item `GenerateCodeUsageExample` to the expected outputs. 

1. **Potential Bugs:**
   - The changes seem limited to updates in test expectations, which typically do not introduce functional bugs as long as the expected output matches any existing modifications in the source code that generate these outputs.

2. **Security Vulnerabilities:**
   - There do not appear to be any security vulnerabilities introduced by these changes, as they involve modifications to test cases and do not interact with any sensitive data or impact application security.

3. **Coding Standards:**
   - Assuming that the original coding standards were followed in the structure of test cases and naming conventions, this change adheres to those same standards. There are no code style issues visible in this diff.

It is important to verify that the tests pass successfully by running them after merging to ensure they align correctly with any changes in the application logic regarding `GenerateCodeUsageExample`.

</div>

**Review by jonahdc — APPROVED** [review]

**Comment by patched-admin** [comment]
The pull request review highlights several key issues, including a potential bug due to the removal of the `@define` decorator and `Comment` class definition, which might affect code functionality if `Comment` is used elsewhere. Security concerns are addressed regarding exception logging in the `create_comment` method, advising caution on logging sensitive information. Code standards compliance issues are noted, such as redundant logging in `get_slug_and_id_from_url`, typographical formatting to improve readability, and better exception handling for type conversions. There is a simplification in the `test` method, with a recommendation for clarity on logic checks. Type hinting is deemed consistent with Python standards. The version update in `pyproject.toml` from 0.0.85 to 0.0.86 presents no bugs or security issues but suggests adding a description for transparency. In a test file, the addition of 'GenerateCodeUsageExample' suggests ensuring its consistency with application code functionality to prevent test failures. Overall, improvements are focused on maintaining functionality, security, and adherence to coding standards.

------

<div markdown="1">

* File changed: [patchwork/common/client/scm.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-a4a0213f577e66fc33444faad6c1991a8c60deb8fc7d5b5527069a66f59804f5)
  1. **Potential Bug:**
   - The removal of `@define` and the `Comment` class definition might lead to an error where `Comment` is used later in the code as it is not imported or redefined elsewhere in the diff. This could be a potential bug, as `Comment` is used in creating comments on pull requests.

2. **Security Vulnerabilities:**
   - **Error Logging:** When logging exceptions in the `create_comment` method (`logger.error(e)`), ensure no sensitive information is leaked through the logs. Depending on the context of when `create_comment` is called, the exception `e` might contain sensitive information that should not be logged.

3. **Code Standards Compliance:**
   - **Redundant Logging:** The method `get_slug_and_id_from_url` uses `logger.error` multiple times. This goes against standard practices if those logs do not provide actionable insights, especially if those errors do not terminate the current operation or cannot be fixed by the information given in logs.
   - **Typographical Formatting:** The split following the `\` character should maintain prior context or line arrangement to enhance readability. While PEP 8 allows the backslash for line continuation, using parentheses is considered more visually consistent and less error-prone.
   - **Use of Try-Except for Type Conversion:** The `get_slug_and_id_from_url` method uses a broad `except` clause when parsing the URL resource ID. It would be better practice to narrow the caught exception types or provide a clearer handling strategy.

4. **Functional Changes:**
   - The `test` method is simplified, which improves clarity. However, confirming that `proj` is the intended method datum for validity would ensure the modification indeed reflects a logic truth test. More context or comments explaining why `ValueError` would arise could aid understanding.

5. **Type Hinting:**
   - The integration of return type hints appears consistent with the function signatures' intended outputs (e.g., `GithubPullRequest`), leading to good adherence to Python typing standards.

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/1142/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  The change is a simple version update from 0.0.85 to 0.0.86 in the `pyproject.toml` file. 

- **Bugs**: This change does not introduce potential bugs as it is purely a change in the metadata/version.
- **Security Vulnerabilities**: There are no direct security implications in this version number change itself. However, it is important to ensure that related changes in the software that justify the version bump have been properly reviewed for security issues.
- **Coding Standards**: The change adheres to the typical version bump practice in versioning systems; however, the description field is left blank, which might not conform to the coding or documentation standards if descriptions are usually provided for releases in this project. It might be beneficial to add meaningful descriptions for clarity and maintain communication standards.

</div>

<div markdown="1">

* File changed: [tests/common/test_app.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)
  The changes in the code are within a test file, specifically adding a new option 'GenerateCodeUsageExample' to the expected test output list. Here are some considerations:

1. **Consistency with Code Standards:** Ensure that 'GenerateCodeUsageExample' is consistently added to the actual application code wherever similar options are utilized. The tests should reflect the actual state of the application.

2. **Introduction of Bugs:** Verify if 'GenerateCodeUsageExample' is an implemented feature or option within the application logic. If it is not yet implemented, adding it to the test expected output could cause the test to fail.

3. **No Obvious Security Vulnerabilities:** Since the changes are within a test and merely update an expected output, there's no direct introduction of security vulnerabilities from this diff specifically.

Overall, ensure that related logic around 'GenerateCodeUsageExample' is correctly implemented in the main application to avoid unnecessary test failures.

</div>

**Comment by patched-admin** [comment]
The pull request review identifies several key areas of concern in the proposed code changes, including potential bugs, security vulnerabilities, adherence to coding standards, and redundant operations. It highlights a potential bug in the `get_slug_and_id_from_url` method due to its assumption of a specific URL format, leading to incorrect parsing. Security concerns are raised regarding the `create_comment` method's direct logging of exceptions without sanitization, while the handling of `azuredevops_api_key` lacks validation or encryption measures, potentially introducing security vulnerabilities. The review also questions the updated type adherence in methods like `find_pr_by_id`, potentially affecting polymorphism and interface usage, and the removal of input validation checks with `required_keys` which might lead to runtime errors. Redundant fetching operations in the `texts` method and limited exception handling in the `test` method are flagged for potential improvement. Unused imports such as `urlparse` are noted for removal, and the switch from the old `Comment` class requires thorough integration to prevent inconsistencies. Overall, the review emphasizes the need for comprehensive exception handling, secure API key management, and adherence to coding standards, including proper documentation. The changes to `pyproject.toml` and test files were found to adhere to coding standards without introducing new issues.

------

<div markdown="1">

* File changed: [patchwork/common/client/scm.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-a4a0213f577e66fc33444faad6c1991a8c60deb8fc7d5b5527069a66f59804f5)
  1. **Potential Bug**: In the `get_slug_and_id_from_url` method, the URL splitting logic assumes a specific format for the URL, which may not be consistent across different users' configurations or repositories. This could lead to incorrect parsing and erroneous outputs.

2. **Security Concerns**: In the `create_comment` method, exceptions are logged directly without any sanitization or classification. Sensitive information could be exposed if exceptions contain any sensitive data. It would be better to have more granular exception handling and logging mechanisms that can categorize exceptions appropriately and log messages without sensitive details.

3. **Coding Standards**: The method signatures for converting types (e.g., `GitlabMergeRequest`, `GithubPullRequest`) in `find_pr_by_id`, `get_pr_by_url`, etc., seem changed from a general `PullRequestProtocol`. Ensure that this updated type adherence aligns with your project's planned refactoring strategy, as it might have implications on polymorphism and interface usage elsewhere in your codebase.

4. **Redundant Fetch**: In `texts` method, the invocation of `for remote in repo.remotes: remote.fetch()` updates the state of the local repository with the remote refs but may not be necessary for constructing diffs from commits that are already locally available. Consider if this fetch is needed or if it should be made conditional.

5. **Error Handling**: In the method `test`, only a `ValueError` exception is caught, which might not be comprehensive enough for the potential exceptions that can be raised by `self.project`. Implementing broader exception handling can enhance robustness. This same issue is present in multiple methods throughout the codebase, and a consistent strategy should be applied for exception handling.

6. **Unused Imports**: There might be unused imports (e.g., `urlparse` and `define`) removed, ensure these were not needed elsewhere before removal.

7. **Differing Comment Structures**: The old `Comment` class was removed. Ensure the code using the related comment structures was entirely modified to suit the new way comments are handled to avoid runtime errors or logical inconsistencies.

</div>

<div markdown="1">

* File changed: [patchwork/steps/CreatePRComment/CreatePRComment.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-12b1995fb92145cce8cba1f9e6fd8553d2c1ac4a8d6caa369fec543f60a14a4b)
  1. **Potential Bugs**:
   - The code currently doesn't handle the case where neither `github_api_key`, `gitlab_api_key`, nor `azuredevops_api_key` is provided. While there's a ValueError thrown for missing GitHub or GitLab keys, Azure DevOps is not yet integrated within that error message. Update the message to mention `azuredevops_api_key` as well.

2. **Security Vulnerabilities**:
   - Ensure that the `AzureDevopsClient` class does not have any known vulnerabilities when handling API keys. API keys should be stored securely, and the sensitivity of this information should be considered when logging and error handling.

3. **Coding Standards**:
   - The new code appears to follow the original coding standards, as it maintains similar conditional checks for additional API keys and consistency with how different SCM clients are initialized. However, consider using a more standardized approach, such as configuration files or environment variables, for managing API keys securely. 

Overall, ensure that error messages and logging do not expose API keys or sensitive input data, and consider improving the configurability of API key handling to adhere to best practices in security management.

</div>

<div markdown="1">

* File changed: [patchwork/steps/CreatePRComment/typed.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-4a0d54503f40d3616fb1f410b35233850e5de1317b6e9491509eda476754c48b)
  1. **Security Vulnerability:** Adding the `azuredevops_api_key` alongside `gitlab_api_key` and `github_api_key` without proper validation or encryption could introduce security vulnerabilities. Ensure that API keys are stored securely and validate them properly to prevent unauthorized access.

2. **Coding Standards:** It is not clear if the introduction of `azuredevops_api_key` adheres to the existing coding standards. There should be supporting documentation or comments explaining this addition and how it fits into existing logic and structure.

3. **Potential Bugs:** The logic change with 'or_op' now includes three keys. Ensure there is test coverage for scenarios involving combinations of these keys to prevent bugs related to order of precedence and unexpected null values.

</div>

<div markdown="1">

* File changed: [patchwork/steps/ReadPRDiffs/ReadPRDiffs.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-98bf6d1177ab0c2533443d9ff06b9e82fee1e552e7ac1a1196ee657492f35a61)
  1. **Potential Bugs:**
  - The check for required keys, particularly `"pr_url"`, has been removed (`required_keys` attribute). This may lead to potential issues where the expected URL might be missing from the input, causing runtime errors.
  
2. **Security Vulnerabilities:**
  - Ensure that the handling of SCM clients (Github, Gitlab, AzureDevops) keys is secure to prevent leakage of sensitive information. This code does not seem to implement new input validation or sanitation which could expose the process to injection-like vulnerabilities if user input is not properly validated elsewhere.
  
3. **Adherence to Coding Standards:**
  - It seems like the new initialization condition for `AzureDevopsClient` follows the existing pattern for Github and Gitlab. However, the removal of `required_keys` validation deviates from established practices of input validation as initially present in the code. It might be beneficial to maintain such validation to ensure that all necessary inputs are present before proceeding.

</div>

<div markdown="1">

* File changed: [patchwork/steps/ReadPRDiffs/typed.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-3620f5358988da86a1fa4499b6cbe59782ed86a5f963e2932ce8e1b11a8e19c0)
  1. **Potential Bugs**: 
   - Adding `azuredevops_api_key` alongside existing keys in `or_op` might result in logic issues if the function that uses these keys assumes only two possible options when resolving which API key to use. Ensure the function logic that processes `or_op` can handle more than two scenarios correctly.

2. **Security Vulnerabilities**: 
   - Introducing another API key handling introduces potential security risks, especially concerning secure storage and proper access management. Ensure that `azuredevops_api_key` receives equivalent handling in terms of secure storage and access restrictions as the other API keys in the system.

3. **Coding Standards**: 
   - Assuming the previous configuration for `or_op` was meant to maintain exactly two keys, introducing a third (`azuredevops_api_key`) changes the underlying assumptions of this logic. Check if the widening of options adheres to the intended design pattern or if additional logic is required to accommodate a third option properly.
   - Ensure that documentation and inline comments are updated to reflect the changes appropriately for maintainability and clarity, especially with the introduction of `azuredevops_api_key`.

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/1142/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  The change in 'pyproject.toml' is an update of the version number for the package 'patchwork-cli' from '0.0.85' to '0.0.86'. 

- There are no code modifications here that could introduce functional bugs or security vulnerabilities as these changes are limited to metadata. 
- The update itself is in line with the original coding standards for versioning as it follows semantic versioning practices where a patch version is being incremented.

No issues found in this pull request according to the provided instruction.

</div>

<div markdown="1">

* File changed: [tests/common/test_app.py](https://github.com/patched-codes/patchwork/pull/1142/files#diff-2a8b90e5130d5bff7e4c009e616d273a3a9f9cdbf67e31dc9bdba0a9c794418c)
  The given changes are modifications to a test file `test_app.py`, specifically to tests for list options. The addition of `GenerateCodeUsageExample` in the expected list output seems to be a simple addition and doesn't introduce any apparent bugs as it's a straightforward change in test assertions. Here is the review based on instructed points:

- **Potential Bugs**: The change itself does not introduce any immediate bugs as it purely alters expected output lists in test functions.

- **Security Vulnerabilities**: The changes are contained within test files and only alter expected strings, hence they do not introduce new security vulnerabilities.

- **Coding Standards**: The modification follows the existing pattern in the test function and thus adheres to the coding standards applied in other parts of the file.

No issues found related to bugs, security, or code standards in this PR.

</div>

**Pull request merged**
