### PR TITLE
Use mustache to render prompts

### PR DESCRIPTION
**Pull request by CTY-git**

### CODE REVIEW

**Comment by patched-admin** [comment]
The pull request review highlighted the introduction of the 'chevron' library for rendering prompts in the code modifications, which could potentially pose a security risk if the 'partials_path' is not properly handled. It emphasized the importance of validating and securing user input and file paths to prevent injection attacks or unauthorized access. Additionally, it pointed out that using 'random' for generating 'partials_ext' may not align with the original coding standards in the pull request.Overall, no bugs or security vulnerabilities were identified in the version update for 'patchwork-cli' in pyproject.toml, and the addition of the 'chevron' library seemed appropriate and in line with the coding standards.

------

<div markdown="1">

* File changed: [patchwork/steps/PreparePrompt/PreparePrompt.py](https://github.com/patched-codes/patchwork/pull/548/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)
  The code modifications have introduced a new library, 'chevron', for rendering prompts using the render function. This could potentially introduce a new security vulnerability if the 'partials_path' is not properly handled or sanitized. It's crucial to ensure that user input or file paths are properly validated and secured to prevent any injection attacks or unauthorized access. Additionally, the usage of 'random' for generating 'partials_ext' might not adhere to original coding standards in the pull request.

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/548/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  No potential bugs or security vulnerabilities identified in the version update for 'patchwork-cli' in pyproject.toml. The addition of 'chevron' library seems appropriate and aligns with original coding standards in the pull request.

</div>

**Comment by patched-admin** [comment]
The pull request review identified that the code modifications deviate from the original coding standards, specifically with the addition of 'import string' and the use of 'random' for generating 'partials_ext', as well as the introduction of 'chevron.render' for rendering templates which may pose security risks if not properly sanitized. It was recommended to review the use of 'chevron' for rendering templates to prevent any potential security vulnerabilities. However, the README.md file modifications for the ReadPRs module were found to be clear and comprehensive, with no identified issues, while the pyproject.toml file modifications were also approved with the updated version and added dependency 'chevron'.

------

<div markdown="1">

* File changed: [patchwork/steps/PreparePrompt/PreparePrompt.py](https://github.com/patched-codes/patchwork/pull/548/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)
  The code modifications made in the pull request deviate from the original coding standards. The addition of the 'import string' statement and the usage of 'random' for generating 'partials_ext' are not aligned with the existing codebase. Furthermore, introducing 'chevron.render' for rendering templates may have potential security vulnerabilities, especially if the rendered data is not properly sanitized. It would be advisable to review the use of 'chevron' for rendering templates and ensure that it does not introduce any new security risks.

</div>

<div markdown="1">

* File changed: [patchwork/steps/ReadPRs/README.md](https://github.com/patched-codes/patchwork/pull/548/files#diff-ad5954061b44272136445bc907ee9887ff307a7c5aa161c1e1011b89ff352bec)
  The code modifications in the README.md file for the ReadPRs module look good. They provide clear documentation for the inputs, outputs, and usage of the ReadPRs module. No potential bugs, security vulnerabilities, or deviations from coding standards were identified.

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/548/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  No issues found in the pyproject.toml file modifications. The version was updated accordingly and a new dependency 'chevron' was added.

</div>

**Comment by patched-admin** [comment]
The pull request review indicates that the code modifications follow the original coding standards, with no identified bugs or security vulnerabilities. However, it is recommended to add error handling for the render function from the chevron library to prevent unhandled errors, and to consider potential security risks of using random.choices for generating file names. The documentation updates for the ReadPRs Module and the addition of the 'chevron' dependency seem to align with the project's standards.

------

<div markdown="1">

* File changed: [patchwork/steps/Combine/README.md](https://github.com/patched-codes/patchwork/pull/548/files#diff-964fb284596bdfd0da0bd0fddd56b91cecce912d036543f3aad807ef7fe4ae08)
  The modifications in the new code seem to adhere to the original coding standards as described in the pull request. No potential bugs or new security vulnerabilities were identified.

</div>

<div markdown="1">

* File changed: [patchwork/steps/PreparePrompt/PreparePrompt.py](https://github.com/patched-codes/patchwork/pull/548/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)
  The code modifications seem to be missing error handling for the render function from the chevron library. If the render function fails for any reason, there is no try-except block to catch potential exceptions, which could lead to unhandled errors. It is recommended to add appropriate error handling to ensure smooth execution and avoid unexpected crashes. Additionally, using random.choices to generate partials_ext in the render function may introduce a potential security vulnerability by creating unpredictable partials file names. It's important to consider the implications of using random values for filenames, as it could lead to conflicts or unexpected behavior. It is advisable to follow the original coding standards of the project regarding error handling and security practices.

</div>

<div markdown="1">

* File changed: [patchwork/steps/ReadPRs/README.md](https://github.com/patched-codes/patchwork/pull/548/files#diff-ad5954061b44272136445bc907ee9887ff307a7c5aa161c1e1011b89ff352bec)
  The code modifications in the pull request seem to be related to documentation updates for the ReadPRs Module. No potential bugs or security vulnerabilities were introduced. The new code added in the README.md file adheres to the original coding standard in the pull request.

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/548/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  No potential bugs or security vulnerabilities were introduced in this change. The addition of the new dependency 'chevron' is in line with the existing dependencies in the project.

</div>

**Review by codelion — APPROVED** [review]

**Comment by patched-admin** [comment]
Overall, the code modifications in the `README.md` file for the `Combine` module do not introduce any potential bugs or security vulnerabilities, and adhere to the original coding standards in the pull request. However, it is suggested to reconsider the use of the 'random' module for generating partials_ext and to ensure that the partials_dict parameter in the chevron render function is utilized properly. Additionally, adding a newline at the end of the file for better readability is recommended for the ReadPRs Module documentation. The updates for the 'SimplifiedLLMOnce' step within the Patchwork project are focused on documenting inputs and outputs without introducing any issues. The pyproject.toml file modifications, including the addition of the chevron dependency and version update to 0.0.45, also seem to be in line with existing dependencies and standard practices.

------

<div markdown="1">

* File changed: [patchwork/steps/Combine/README.md](https://github.com/patched-codes/patchwork/pull/548/files#diff-964fb284596bdfd0da0bd0fddd56b91cecce912d036543f3aad807ef7fe4ae08)
  The code modifications in the `README.md` file for the `Combine` module do not introduce any potential bugs or security vulnerabilities. The new code in the file adheres to the original coding standards in the pull request.

</div>

<div markdown="1">

* File changed: [patchwork/steps/PreparePrompt/PreparePrompt.py](https://github.com/patched-codes/patchwork/pull/548/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)
  The changes look good overall. However, there are a couple of points to consider - First, the introduction of 'random' module for generating partials_ext might result in unpredictable behavior. It may be clearer to stick to a more standard approach for generating the partials_ext value. Second, the partials_dict parameter in the chevron render function is not being utilized. If it was intended to be used, the necessary logic needs to be added. Apart from these points, there are no potential bugs or security vulnerabilities introduced. The code modifications adhere to the original coding standards in the pull request.

</div>

<div markdown="1">

* File changed: [patchwork/steps/ReadPRs/README.md](https://github.com/patched-codes/patchwork/pull/548/files#diff-ad5954061b44272136445bc907ee9887ff307a7c5aa161c1e1011b89ff352bec)
  The changes for documenting the ReadPRs Module looks good overall. However, it's recommended to add a newline at the end of the file for better readability and consistency.

</div>

<div markdown="1">

* File changed: [patchwork/steps/SimplifiedLLMOnce/README.md](https://github.com/patched-codes/patchwork/pull/548/files#diff-78e38bfb39d37dc58aa992d3e5c637906801ed94cb2f2b353814056a93d2f7eb)
  The code modifications in the README.md file look good in terms of adherence to the original coding standards. However, it appears that the update is only adding documentation for inputs and outputs of the 'SimplifiedLLMOnce' step within the Patchwork project. No potential bugs or security vulnerabilities were identified in this context.

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/548/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  No potential bugs or security vulnerabilities identified in the pyproject.toml file. The addition of chevron dependency seems to be in line with the existing dependencies. The version update to 0.0.45 also appears to be standard practice.

</div>

**Pull request merged**
