### PR TITLE
Support prompt file beside configs

### PR DESCRIPTION
**Pull request by CTY-git**

### CODE REVIEW

**Comment by patched-admin** [comment]
The first code change adds a new function `_get_config_path` that returns a tuple of `config_path` and `prompt_path` by checking for specific files within the provided `config_path`, aiding in obtaining configuration and prompt files. The second change inserts a new key "compatibility" with values into the dictionary "response_partitions" in the __init__ method of the AutoFix class. The third change updates the usage of a constant variable `PROMPT_TEMPLATE_FILE_KEY` instead of a hardcoded string in various parts of the script for consistency and readability when accessing input dictionary values and error messages related to the prompt template file.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The diff in the code adds a new function `_get_config_path` which takes inputs `config` and `patchflow`, and returns a tuple of `config_path` and `prompt_path`. The function checks if the provided `config_path` is a directory and looks for specific files within it, setting `config_path` and `prompt_path` accordingly. This helps in obtaining the necessary configuration and prompt files for processing.](https://github.com/patched-codes/patchwork/pull/23/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [A new key "compatibility" was added to the dictionary "response_partitions" with the values ["C. Compatibility Risk:", "D. Fixed Code:"]. This key was inserted in the __init__ method of the AutoFix class in the AutoFix.py file.](https://github.com/patched-codes/patchwork/pull/23/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/steps/PreparePrompt/PreparePrompt.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)
  [This diff in the code updates the usage of a constant variable `PROMPT_TEMPLATE_FILE_KEY` instead of a hardcoded string "prompt_template_file" in various parts of the script to maintain consistency and readability. The constant is used to access the input dictionary values and error messages related to the specified prompt template file.](https://github.com/patched-codes/patchwork/pull/23/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)

</div>

**Review by codelion — APPROVED** [review]
Add a few changes LTGM!

**Comment by patched-admin** [comment]
The code changes introduce a new function in app.py called _get_config_path to retrieve configuration and prompt file paths, as well as a call to run_chat from the interpreter module. The interpreter.py file now includes a run_chat function to set attributes and prompt the user for an OpenAI Key before calling the chat method. AutoFix.py adds compatibility input to response_partitions dictionary, adjusting commit and patch structures. A new class CallOpenAI is added to CallInterpreter.py to handle API key parameters and chat method execution. Further changes include defining PROMPT_TEMPLATE_FILE_KEY for consistent access, updating dependency versions in pyproject.toml to specify Python version constraints and introduce a new dependency on open-interpreter.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The code in app.py introduces a new function called _get_config_path that takes in two parameters and returns a tuple of Path objects. The function is used to get the paths for the configuration and prompt files based on certain conditions. Additionally, the code now includes a call to the run_chat function from the interpreter module under specific conditions.](https://github.com/patched-codes/patchwork/pull/23/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/interpreter.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-871144dc632f5c7cbd421a5bf13c68d4d8e242319629b6273a4f3a987a962a50)
  [The code in the interpreter.py file now includes a function called run_chat, which sets certain attributes in the interpreter module, sets a banner, prompts the user for an OpenAI Key, and then calls the chat method.](https://github.com/patched-codes/patchwork/pull/23/files#diff-871144dc632f5c7cbd421a5bf13c68d4d8e242319629b6273a4f3a987a962a50)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [An additional input for "compatibility" has been added to the "response_partitions" dictionary in the AutoFix.py file, with a corresponding value range being specified within the patch inputs, affecting the structure and labeling of commits and patches being generated.](https://github.com/patched-codes/patchwork/pull/23/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/steps/CallInterpreter/CallInterpreter.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-27286a62f4ae32358d918777edce5c0f032d4dff848293cfd333fc66815642dd)
  [This diff adds a new Python class called `CallOpenAI` to the `CallInterpreter.py` file. The class initializes with required keys and inputs, sets API key parameters, and runs the interpreter's chat method when the `run` method is called.](https://github.com/patched-codes/patchwork/pull/23/files#diff-27286a62f4ae32358d918777edce5c0f032d4dff848293cfd333fc66815642dd)

</div>

<div markdown="1">

* File changed: [patchwork/steps/PreparePrompt/PreparePrompt.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)
  [In the given diff, the key "PROMPT_TEMPLATE_FILE_KEY" is defined as the value "prompt_template_file" and used to access corresponding values in the code. This change helps in maintaining consistency in the code and improves readability by using the defined constant instead of hardcoded strings.](https://github.com/patched-codes/patchwork/pull/23/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/23/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The diff in the pyproject.toml file updates the dependency versions by changing the Python version constraint from "^3.10" to "~3.10" and the tiktoken version from "^0.6.0" to "~0.5.2". Additionally, it adds a new dependency on open-interpreter with version "~0.2.4".](https://github.com/patched-codes/patchwork/pull/23/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

**Comment by patched-admin** [comment]
Several changes were made in the codebase including adding a new function `_get_config_path` in `app.py` to determine configuration and prompt file paths, incorporating these paths in the `cli` function, adding a `run_chat()` function in `interpreter.py` to set configurations and prompt for an OpenAI key, updating the AutoFix class in AutoFix.py to include a "compatibility" key in the `response_partitions` dictionary, refactoring `PreparePrompt.py` to use a constant variable, updating dependencies in `pyproject.toml` by changing `^3.10` to `~3.10` for python, changing `^0.6.0` to `~0.5.2` for tiktoken, and adding a new dependency `open-interpreter` with version `~0.2.4`.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [This diff adds a new function `_get_config_path` in the `app.py` file which takes in a `config` and `patchflow` argument to determine the configuration and prompt file paths. It also incorporates the use of these paths to load the configuration and prompt data within the `cli` function when provided with a `config` argument.](https://github.com/patched-codes/patchwork/pull/23/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/interpreter.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-871144dc632f5c7cbd421a5bf13c68d4d8e242319629b6273a4f3a987a962a50)
  [The patch adds a new function `run_chat()` to the `interpreter.py` file, which sets some configurations for the interpreter and prompts the user to enter an OpenAI key for the interpreter to use. It also includes a decorative banner and sets the model to "gpt-3.5-turbo" before running the chat functionality.](https://github.com/patched-codes/patchwork/pull/23/files#diff-871144dc632f5c7cbd421a5bf13c68d4d8e242319629b6273a4f3a987a962a50)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [An additional key "compatibility" was added to the "response_partitions" dictionary in the `__init__` function of the AutoFix class in AutoFix.py.; This key has values corresponding to the labels "C. Compatibility Risk:" and "D. Fixed Code:".; The PR title for the commit is set using the class name of AutoFix.](https://github.com/patched-codes/patchwork/pull/23/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/steps/PreparePrompt/PreparePrompt.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)
  [The code in PreparePrompt.py has been modified to use a constant variable PROMPT_TEMPLATE_FILE_KEY instead of hardcoding a string value. This change is implemented in multiple places within the code for better maintainability and readability.](https://github.com/patched-codes/patchwork/pull/23/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/23/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version of `python` dependency in the `pyproject.toml` file was changed from `^3.10` to `~3.10`, and the version of `tiktoken` dependency was changed from `^0.6.0` to `~0.5.2`. Additionally, a new dependency `open-interpreter` with version `~0.2.4` was added in the file.](https://github.com/patched-codes/patchwork/pull/23/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

**Comment by patched-admin** [comment]
The code changes involve adding a new function to handle configuration and prompt file paths and update the `inputs` dictionary, creating a `run_chat()` function to set parameters for the `interpreter` class, adding a key-value pair in the initialization method of the AutoFix class for compatibility risk, using a constant instead of a hardcoded string in the `PreparePrompt` class, and updating Python version constraints and library dependencies in the `pyproject.toml` file. These changes aim to enhance functionality, readability, and maintainability in the codebase.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The code includes a new function `_get_config_path(config: str, patchflow: str) -> tuple[Path | None, Path | None]:` which creates paths for configuration and prompt files based on given parameters. It retrieves the configuration and prompt paths, attempting to load them and update the `inputs` dictionary used in the CLI. Additionally, the function handles error cases where the files are not found or sets the `PreparePrompt.PROMPT_TEMPLATE_FILE_KEY` if a prompt file is present.](https://github.com/patched-codes/patchwork/pull/23/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/interpreter.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-871144dc632f5c7cbd421a5bf13c68d4d8e242319629b6273a4f3a987a962a50)
  [This diff adds a new function `run_chat()` to import the `getpass` module and set parameters for the `interpreter` class. It initializes the model, sets the API key for the interpreter, prints a banner, and prompts the user to enter their OpenAI key before starting the chat session.](https://github.com/patched-codes/patchwork/pull/23/files#diff-871144dc632f5c7cbd421a5bf13c68d4d8e242319629b6273a4f3a987a962a50)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [In the given diff, a new line is added to the initialization method of the AutoFix class in AutoFix.py file. This line adds a key-value pair to the final_inputs dictionary for handling compatibility risk in the response_partitions section.](https://github.com/patched-codes/patchwork/pull/23/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/steps/PreparePrompt/PreparePrompt.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)
  [The diff involves updating the code in the `PreparePrompt` class to use a constant `PROMPT_TEMPLATE_FILE_KEY` instead of a hardcoded string for accessing the value from `inputs`. This change aims to improve code readability and maintainability by using a named constant for the key.](https://github.com/patched-codes/patchwork/pull/23/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/23/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [Updated the Python version constraint from "^3.10" to "~3.10" in the `pyproject.toml` file. Also, changed the version constraint for the `tiktoken` library from "^0.6.0" to "~0.5.2" and added a new dependency `open-interpreter` with version "~0.2.4".](https://github.com/patched-codes/patchwork/pull/23/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

**Comment by patched-admin** [comment]
The code changes include adding a new method in app.py to retrieve configuration and prompt paths, introducing a function in interpreter.py for enabling chatting with OpenAI API, adding a compatibility key to the response_partitions dictionary in AutoFix class, implementing a constant key in PreparePrompt.py for clarity, and updating version numbers and dependencies in pyproject.toml for patchwork-cli project.

------

<div markdown="1">

* File changed: [patchwork/app.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)
  [The diff shows changes in the app.py file, where a new method called _get_config_path is added to retrieve configuration and prompt paths. The method checks for the existence of the configuration and prompt files and returns their paths or None. The retrieved paths are then used to load configuration data and add a prompt template file key to the inputs dictionary for the Patchwork application.](https://github.com/patched-codes/patchwork/pull/23/files#diff-839e90b808d34e4cf447eff0896161788ccfc6e1f2970be2e551b64ba413a503)

</div>

<div markdown="1">

* File changed: [patchwork/interpreter.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-871144dc632f5c7cbd421a5bf13c68d4d8e242319629b6273a4f3a987a962a50)
  [This diff adds a new function `run_chat()` in the `interpreter.py` file, which sets the verbose mode to false, specifies a model, prints a banner, and takes the OpenAI key to enable chatting functionality using the OpenAI API.](https://github.com/patched-codes/patchwork/pull/23/files#diff-871144dc632f5c7cbd421a5bf13c68d4d8e242319629b6273a4f3a987a962a50)

</div>

<div markdown="1">

* File changed: [patchwork/patchflows/AutoFix/AutoFix.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)
  [In this code change, a new key "compatibility" is added to the "response_partitions" dictionary within the AutoFix class, which is positioned after the "patch_message" key. This new key is used to store the information related to compatibility risk associated with the patch.](https://github.com/patched-codes/patchwork/pull/23/files#diff-cfe3d043784d0e098457916dd63bfaa77446b4a12c8677b65fc68aadd64360ec)

</div>

<div markdown="1">

* File changed: [patchwork/steps/PreparePrompt/PreparePrompt.py](https://github.com/patched-codes/patchwork/pull/23/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)
  [The code in PreparePrompt.py has been modified to use a constant PROMPT_TEMPLATE_FILE_KEY in place of specific string values, in order to refer to keys in the inputs dictionary consistently throughout the code. This change ensures clarity and maintainability in the implementation.](https://github.com/patched-codes/patchwork/pull/23/files#diff-a1fa6ea12e14a0cc254b863d724e90d8aa3ce41f3d4fdbb876100f3b3a2a70c8)

</div>

<div markdown="1">

* File changed: [pyproject.toml](https://github.com/patched-codes/patchwork/pull/23/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
  [The version of the project "patchwork-cli" in the pyproject.toml file has been updated from 0.0.5 to 0.0.6. Additionally, the version constraint for the package "tiktoken" has been changed from "^0.6.0" to "~0.5.2", and a new dependency "open-interpreter" with version "~0.2.4" has been added.](https://github.com/patched-codes/patchwork/pull/23/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

</div>

**Pull request merged**
