### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by codelion**
Fix typo.

### CODE REVIEW

**Comment by patched-admin** [comment]
The pull request review is for a simple typo fix in the README.md file, with no impact on potential bugs or security vulnerabilities. The change is in line with the coding standards of the repository and has been approved for merging.

------

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/410/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  The pull request only includes a fix for a typo in the README.md file, which does not introduce any potential bugs or security vulnerabilities. The change aligns with the original coding standards in the repository. Approved for merging.

</div>

**Comment by patched-admin** [comment]
The review of this pull request indicates that the code modifications in INSTALL.md are adding a new section for installation instructions for macOS using brew, which does not introduce any bugs, security vulnerabilities, or violations of coding standards. Additionally, a typo in the README.md file has been fixed, making the changes in this pull request seem positive and well-executed.

------

<div markdown="1">

* File changed: [INSTALL.md](https://github.com/patched-codes/patchwork/pull/410/files#diff-09b140a43ebfdd8dbec31ce72cafffd15164d2860fd390692a030bcb932b54a0)
  The code modifications in INSTALL.md seem to be adding a new section to include installation instructions for macOS using brew. This addition does not introduce any potential bugs, security vulnerabilities, or coding standard violations.

</div>

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/410/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  The code modifications in this pull request look good. The typo has been fixed in the README.md file.

</div>

**Comment by patched-admin** [comment]
The pull request is positive as it fixes a typo in the README.md file by updating 'gruntwwork' to 'gruntwork'. There are no potential bugs or security vulnerabilities introduced, and the code modification aligns with the original coding standards in the pull request.

------

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/410/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  The pull request looks good. It fixes a typo in the README.md file, updating 'gruntwwork' to 'gruntwork'. No potential bugs or security vulnerabilities introduced. The code modification adheres to the original coding standards in the pull request.

</div>

**Comment by patched-admin** [comment]
This pull request is a minor fix to correct a typo in the README.md file. The changes do not introduce any potential bugs or security vulnerabilities, and the new code follows the original coding standards outlined in the pull request.

------

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/410/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  The pull request is a minor fix to correct a typo in the README.md file. No potential bugs or security vulnerabilities have been introduced. The new code adheres to the original coding standards in the pull request.

</div>

**Comment by patched-admin** [comment]
The pull request addresses a typo in the README.md file, but the added code snippets for using open source models lack input validation, which could pose security risks if an unsupported model is provided. It is suggested to implement input validation to only allow supported model names and to ensure consistency in the indentation of the code block with the existing format in the file.

------

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/410/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  The pull request effectively fixes a typo in the README.md file. However, the new code additions for using open source models seem to lack proper input validation. Specifically, the code snippets provided for using different models do not validate the input 'model' against a predefined list of supported models, which could potentially lead to unintended behavior or security risks if a non-supported model is provided. It would be beneficial to add input validation to ensure only valid model names are accepted. Additionally, the indentation in the added code block is inconsistent with the existing code format in the file.

</div>

**Comment by codelion** [comment]
also fixes #414

**Comment by patched-admin** [comment]
The pull request is a simple fix for a typo in the README.md file, with no bugs or security issues identified. The new code added conforms to the existing coding standards, making it a straightforward and safe change.

------

<div markdown="1">

* File changed: [README.md](https://github.com/patched-codes/patchwork/pull/410/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  The pull request fixes a typo in the README.md file. No potential bugs or security vulnerabilities were identified. The new code added in the pull request adheres to the original coding standards.

</div>

**Review by CTY-git — APPROVED** [review]

**Pull request merged**
